
CREATE     VIEW [hmi].[V_AS_WorkOrders]
AS SELECT WO.FactWorkOrderKey AS DimWorkOrderId, 
          WO.WorkOrderName AS DimWorkOrderName, 
          WO.DimYear, 
          WO.DimMonth, 
          WO.DimWeek, 
          WO.DimDate, 
          WO.DimShiftCode, 
          WO.DimShiftKey, 
          WO.DimCrewName, 
          WO.DimMaterialCatalogueName, 
          WO.DimProductCatalogueName, 
          WO.DimProductThickness, 
          WO.DimSteelgradeName, 
          WO.DimHeatName, 
          WO.WorkOrderTargetWeight AS TargetWeight, 
          WO.WorkOrderMaterialNumber AS MaterialsNumber, 
          WO.WorkOrderMaterialWeight AS MaterialsWeight, 
          WO.WorkOrderRawMaterialNumber AS RawMaterialsNumber, 
          WO.WorkOrderRawMaterialWeight AS RawMaterialsWeight, 
          WO.WorkOrderProductNumber AS ProductsNumber, 
          WO.WorkOrderProductWeight AS ProductsWeight, 
          WO.WorkOrderScrappedNumber AS MaterialsScrappedNumber, 
		  WO.WorkOrderScrappedWeight AS MaterialsScrappedWeight,
          WO.WorkOrderDuration AS ProductionTime, 
          WO.WorkOrderRollingDuration AS RollingTime,
          WO.WorkOrderDelayDuration AS DelayDuration, 
          WO.WorkOrderMetallicYield AS MetallicYield, 
          WO.WorkOrderQualityYield AS QualityYield
   FROM dw.FactWorkOrder AS WO;