CREATE TABLE [stage].[RawMaterials] (
    [RawMaterialId]         BIGINT         IDENTITY (1, 1) NOT NULL,
    [AUDCreatedTs]          DATETIME       NOT NULL,
    [AUDLastUpdatedTs]      DATETIME       NOT NULL,
    [AUDUpdatedBy]          NVARCHAR (200) NULL,
    [IsDeleted]             BIT            NOT NULL,
    [IsBeforeCommit]        BIT            NOT NULL,
    [FKShiftCalendarId]     BIGINT         NOT NULL,
    [FKLastAssetId]         BIGINT         NULL,
    [FKMaterialId]          BIGINT         NULL,
    [FKProductId]           BIGINT         NULL,
    [FKParentRawMaterialId] BIGINT         NULL,
    [FKParentLayerId]       BIGINT         NULL,
    [RawMaterialName]       NVARCHAR (50)  NOT NULL,
    [OldRawMaterialName]    NVARCHAR (50)  NULL,
    [IsDummy]               BIT            NOT NULL,
    [IsVirtual]             BIT            NOT NULL,
    [IsLayer]               BIT            NOT NULL,
    [EnumRawMaterialStatus] SMALLINT       NOT NULL,
    [CuttingSeqNo]          SMALLINT       NOT NULL,
    [ChildsNo]              SMALLINT       NOT NULL,
    [EnumLayerStatus]       SMALLINT       NOT NULL,
    [EnumChargeType]        SMALLINT       NOT NULL,
    [SlittingFactor]        SMALLINT       NULL,
    [LastWeight]            FLOAT (53)     NULL,
    [LastLength]            FLOAT (53)     NULL,
    [LastTemperature]       FLOAT (53)     NULL,
    [ProductCreatedTs]      DATETIME       NULL,
    [RawMaterialCreatedTs]  DATETIME       NOT NULL,
    [EnumTypeOfScrap]       SMALLINT       NOT NULL,
    [ScrapPercent]          FLOAT (53)     NULL,
    [FKScrapAssetId]        BIGINT         NULL,
    [ScrapRemarks]          NVARCHAR (200) NULL
);

