CREATE TABLE [stage].[WorkOrders] (
    [WorkOrderId]            BIGINT         IDENTITY (1, 1) NOT NULL,
    [AUDCreatedTs]           DATETIME       NOT NULL,
    [AUDLastUpdatedTs]       DATETIME       NOT NULL,
    [AUDUpdatedBy]           NVARCHAR (200) NULL,
    [IsDeleted]              BIT            NOT NULL,
    [IsBeforeCommit]         BIT            NOT NULL,
    [FKProductCatalogueId]   BIGINT         NOT NULL,
    [FKMaterialCatalogueId]  BIGINT         NOT NULL,
    [FKSteelgradeId]         BIGINT         NULL,
    [FKHeatId]               BIGINT         NULL,
    [FKCustomerId]           BIGINT         NULL,
    [FKParentWorkOrderId]    BIGINT         NULL,
    [EnumWorkOrderStatus]    SMALLINT       NOT NULL,
    [WorkOrderName]          NVARCHAR (50)  NOT NULL,
    [WorkOrderCreatedInL3Ts] DATETIME       NOT NULL,
    [WorkOrderCreatedTs]     DATETIME       NOT NULL,
    [WorkOrderStartTs]       DATETIME       NULL,
    [WorkOrderEndTs]         DATETIME       NULL,
    [ToBeCompletedBeforeTs]  DATETIME       NOT NULL,
    [IsTestOrder]            BIT            NOT NULL,
    [IsBlocked]              BIT            NOT NULL,
    [TargetOrderWeight]      FLOAT (53)     NOT NULL,
    [TargetOrderWeightMin]   FLOAT (53)     NULL,
    [TargetOrderWeightMax]   FLOAT (53)     NULL,
    [BundleWeightMin]        FLOAT (53)     NULL,
    [BundleWeightMax]        FLOAT (53)     NULL,
    [EnumSetupAssign]        SMALLINT       NOT NULL,
    [L3NumberOfBillets]      SMALLINT       NOT NULL,
    [ExternalWorkOrderName]  NVARCHAR (50)  NULL
);

