CREATE TABLE [dw].[DimDate] (
    [SourceName]        NVARCHAR (50)  NOT NULL,
    [SourceTime]        DATETIME       NOT NULL,
    [DimDateIsDeleted]  BIT            NOT NULL,
    [DimDateHash]       VARBINARY (16) NULL,
    [DimDateKey]        INT            NOT NULL,
    [DimCalendarKey]    BIGINT         NOT NULL,
    [DimYearKey]        INT            NOT NULL,
    [DateHalfOfYear]    INT            NOT NULL,
    [DateQuarter]       INT            NOT NULL,
    [DateMonth]         INT            NOT NULL,
    [DateWeek]          INT            NOT NULL,
    [DateWeekISO]       INT            NOT NULL,
    [DateDayOfYear]     INT            NOT NULL,
    [DateDayOfMonth]    INT            NOT NULL,
    [DateDayOfWeek]     INT            NOT NULL,
    [DateIsWeekend]     BIT            NOT NULL,
    [DateMonthName]     NVARCHAR (30)  NOT NULL,
    [DateWeekDayName]   VARCHAR (10)   NOT NULL,
    [DateFullDateTime]  DATETIME       NOT NULL,
    [DateFullDateTime2] DATETIME2 (3)  NOT NULL,
    [DateFullDate]      DATE           NOT NULL,
    [DateANSI]          VARCHAR (10)   NOT NULL,
    [DateUS]            VARCHAR (10)   NOT NULL,
    [DateUK]            VARCHAR (10)   NOT NULL,
    [DateDE]            VARCHAR (10)   NOT NULL,
    [DateIT]            VARCHAR (10)   NOT NULL,
    [DateISO]           VARCHAR (8)    NOT NULL,
    [DateFirstOfYear]   DATE           NOT NULL,
    [DateLastOfYear]    DATE           NOT NULL,
    [DateFirstOfMonth]  DATE           NOT NULL,
    [DateLastOfMonth]   DATE           NOT NULL,
    [DateYearMonth]     VARCHAR (7)    NOT NULL,
    [DateYearWeek]      VARCHAR (8)    NOT NULL,
    [DateYearQuarter]   VARCHAR (7)    NOT NULL,
    [DimDateRow]        INT            IDENTITY (1, 1) NOT NULL
);

