CREATE TABLE [dw].[DimHeat] (
    [SourceName]              NVARCHAR (50)  NOT NULL,
    [SourceTime]              DATETIME       NOT NULL,
    [DimHeatIsDeleted]        BIT            NOT NULL,
    [DimHeatHash]             VARBINARY (16) NULL,
    [DimHeatKey]              BIGINT         NOT NULL,
    [DimSteelgradeKey]        BIGINT         NULL,
    [DimHeatSupplierKey]      BIGINT         NULL,
    [HeatName]                NVARCHAR (50)  NOT NULL,
    [HeatWeight]              FLOAT (53)     NULL,
    [HeatCreated]             DATETIME       NULL,
    [SteelgradeName]          NVARCHAR (50)  NULL,
    [HeatSupplierName]        NVARCHAR (50)  NULL,
    [HeatSupplierDescription] NVARCHAR (200) NULL,
    [HeatChFe]                FLOAT (53)     NULL,
    [HeatChC]                 FLOAT (53)     NULL,
    [HeatChMn]                FLOAT (53)     NULL,
    [HeatChCr]                FLOAT (53)     NULL,
    [HeatChMo]                FLOAT (53)     NULL,
    [HeatChV]                 FLOAT (53)     NULL,
    [HeatChNi]                FLOAT (53)     NULL,
    [HeatChCo]                FLOAT (53)     NULL,
    [HeatChSi]                FLOAT (53)     NULL,
    [HeatChP]                 FLOAT (53)     NULL,
    [HeatChS]                 FLOAT (53)     NULL,
    [HeatChCu]                FLOAT (53)     NULL,
    [HeatChNb]                FLOAT (53)     NULL,
    [HeatChAl]                FLOAT (53)     NULL,
    [HeatChN]                 FLOAT (53)     NULL,
    [HeatChCa]                FLOAT (53)     NULL,
    [HeatChB]                 FLOAT (53)     NULL,
    [HeatChTi]                FLOAT (53)     NULL,
    [HeatChSn]                FLOAT (53)     NULL,
    [HeatChO]                 FLOAT (53)     NULL,
    [HeatChH]                 FLOAT (53)     NULL,
    [HeatChW]                 FLOAT (53)     NULL,
    [HeatChPb]                FLOAT (53)     NULL,
    [HeatChZn]                FLOAT (53)     NULL,
    [HeatChAs]                FLOAT (53)     NULL,
    [HeatChMg]                FLOAT (53)     NULL,
    [HeatChSb]                FLOAT (53)     NULL,
    [HeatChBi]                FLOAT (53)     NULL,
    [HeatChTa]                FLOAT (53)     NULL,
    [HeatChZr]                FLOAT (53)     NULL,
    [HeatChCe]                FLOAT (53)     NULL,
    [HeatChTe]                FLOAT (53)     NULL,
    [DimHeatRow]              INT            IDENTITY (1, 1) NOT NULL
);

