CREATE TABLE [dw].[FactWorkOrder] (
    [SourceName]                         NVARCHAR (50)   NOT NULL,
    [SourceTime]                         DATETIME        NOT NULL,
    [FactWorkOrderIsDeleted]             BIT             NOT NULL,
    [FactWorkOrderHash]                  VARBINARY (16)  NULL,
    [FactWorkOrderKey]                   BIGINT          NOT NULL,
    [FactWorkOrderKeyParent]             BIGINT          NULL,
    [DimYearKey]                         INT             NOT NULL,
    [DimDateKey]                         INT             NOT NULL,
    [DimYear]                            NVARCHAR (4000) NULL,
    [DimMonth]                           NVARCHAR (4000) NULL,
    [DimWeek]                            NVARCHAR (4000) NOT NULL,
    [DimDate]                            NVARCHAR (4000) NULL,
    [DimShiftCode]                       NVARCHAR (10)   NULL,
    [DimShiftKey]                        NVARCHAR (51)   NULL,
    [DimCrewName]                        NVARCHAR (50)   NULL,
    [DimMaterialCatalogueKey]            BIGINT          NOT NULL,
    [DimMaterialCatalogueName]           NVARCHAR (50)   NOT NULL,
    [DimProductCatalogueKey]             BIGINT          NOT NULL,
    [DimProductCatalogueName]            NVARCHAR (50)   NOT NULL,
    [DimProductThickness]                VARCHAR (30)    NULL,
    [DimSteelgradeKey]                   BIGINT          NOT NULL,
    [DimSteelgradeCode]                  NVARCHAR (10)   NOT NULL,
    [DimSteelgradeName]                  NVARCHAR (50)   NULL,
    [DimSteelGroupKey]                   BIGINT          NULL,
    [DimScrapGroupKey]                   BIGINT          NULL,
    [DimHeatKey]                         BIGINT          NULL,
    [DimHeatName]                        NVARCHAR (50)   NULL,
    [DimCustomerKey]                     BIGINT          NULL,
    [DimWorkOrderStatusKey]              SMALLINT        NOT NULL,
    [WorkOrderName]                      NVARCHAR (50)   NOT NULL,
    [WorkOrderCreated]                   DATETIME        NOT NULL,
    [WorkOrderCreatedInL3]               DATETIME        NOT NULL,
    [WorkOrderDueDate]                   DATETIME        NOT NULL,
    [WorkOrderStart]                     DATETIME        NULL,
    [WorkOrderEnd]                       DATETIME        NULL,
    [WorkOrderExternalName]              NVARCHAR (50)   NULL,
    [WorkOrderDuration]                  BIGINT          NOT NULL,
    [WorkOrderDurationFT]                NVARCHAR (30)   NOT NULL,
    [WorkOrderIsTest]                    BIT             NOT NULL,
    [WorkOrderTargetWeight]              FLOAT (53)      NOT NULL,
    [WorkOrderTargetMinWeight]           FLOAT (53)      NULL,
    [WorkOrderTargetMaxWeight]           FLOAT (53)      NULL,
    [WorkOrderMaterialNumber]            INT             NULL,
    [WorkOrderMaterialWeight]            FLOAT (53)      NULL,
    [WorkOrderProductNumber]             INT             NOT NULL,
    [WorkOrderProductWeight]             FLOAT (53)      NOT NULL,
    [WorkOrderProductWeightBad]          FLOAT (53)      NOT NULL,
    [WorkOrderRawMaterialNumber]         INT             NOT NULL,
    [WorkOrderRawMaterialWeight]         FLOAT (53)      NOT NULL,
    [WorkOrderRejectedWeight]            FLOAT (53)      NOT NULL,
    [WorkOrderRejectedNumber]            INT             NOT NULL,
    [WorkOrderScrappedWeight]            FLOAT (53)      NOT NULL,
    [WorkOrderScrappedNumber]            INT             NOT NULL,
    [MinFurnaceExitTemperature]          FLOAT (53)      NULL,
    [MaxFurnaceExitTemperature]          FLOAT (53)      NULL,
    [AvgFurnaceExitTemperature]          FLOAT (53)      NULL,
    [MinSpeed]                           NUMERIC (1, 1)  NULL,
    [MaxSpeed]                           NUMERIC (1, 1)  NULL,
    [AvgSpeed]                           NUMERIC (1, 1)  NULL,
    [MinRollGap]                         NUMERIC (1, 1)  NULL,
    [MaxRollGap]                         NUMERIC (1, 1)  NULL,
    [AvgRollGap]                         NUMERIC (1, 1)  NULL,
    [WorkOrderDelayDuration]             BIGINT          NOT NULL,
    [WorkOrderRollingDuration]           BIGINT          NULL,
    [WorkOrderMetallicYield]             FLOAT (53)      NULL,
    [WorkOrderQualityYield]              FLOAT (53)      NULL,
    [WorkOrderProductionPlanVariance]    FLOAT (53)      NULL,
    [WorkOrderTestTimePercentageOfTotal] FLOAT (53)      NULL,
    [WorkOrderStatus]                    VARCHAR (50)    NULL,
    [FactWorkOrderRow]                   BIGINT          IDENTITY (1, 1) NOT NULL
);





