CREATE TABLE [dw].[FactEvent] (
    [SourceName]                 NVARCHAR (50)  NOT NULL,
    [SourceTime]                 DATETIME       NOT NULL,
    [FactEventIsDeleted]         BIT            NOT NULL,
    [FactEventHash]              VARBINARY (16) NULL,
    [FactEventKey]               BIGINT         NOT NULL,
    [FactEventKeyParent]         BIGINT         NULL,
    [DimEventTypeKey]            BIGINT         NOT NULL,
    [DimRootEventTypeKey]        BIGINT         NOT NULL,
    [DimEventCatalogueKey]       BIGINT         NULL,
    [DimYearKey]                 INT            NOT NULL,
    [DimDateKey]                 INT            NOT NULL,
    [DimShiftKey]                BIGINT         NULL,
    [DimWorkOrderKey]            BIGINT         NULL,
    [DimAssetKey]                BIGINT         NULL,
    [DimRawMaterialKey]          BIGINT         NULL,
    [DimMaterialKey]             BIGINT         NULL,
    [DimUserKey]                 NVARCHAR (450) NULL,
    [EventDayShiftCrew]          NVARCHAR (76)  NOT NULL,
    [EventShiftCode]             NVARCHAR (10)  NULL,
    [EventIsDelay]               BIT            NOT NULL,
    [EventIsPlanned]             BIT            NOT NULL,
    [EventIsOpen]                BIT            NOT NULL,
    [EventTypeCode]              SMALLINT       NOT NULL,
    [EventTypeName]              NVARCHAR (50)  NOT NULL,
    [EventCatalogueCode]         NVARCHAR (10)  NULL,
    [EventCatalogueName]         NVARCHAR (50)  NULL,
    [EventCatalogueCategoryCode] NVARCHAR (10)  NULL,
    [EventCatalogueCategoryName] NVARCHAR (50)  NULL,
    [ScrapPercent]               FLOAT (53)     NULL,
    [MaterialName]               NVARCHAR (50)  NULL,
    [MaterialWeight]             FLOAT (53)     NULL,
    [ProductWeight]              FLOAT (53)     NULL,
    [WorkOrderName]              NVARCHAR (50)  NULL,
    [AssetCode]                  INT            NULL,
    [AssetName]                  NVARCHAR (50)  NULL,
    [RootEventTypeCode]          SMALLINT       NOT NULL,
    [RootEventTypeName]          NVARCHAR (50)  NOT NULL,
    [EventDate]                  DATE           NULL,
    [EventStart]                 DATETIME       NOT NULL,
    [EventEnd]                   DATETIME       NULL,
    [EventStdTime]               FLOAT (53)     NULL,
    [EventUserComment]           NVARCHAR (200) NULL,
    [EventUserUpdated]           DATETIME       NULL,
    [EventDuration]              INT            NOT NULL,
    [EventDurationFD]            NVARCHAR (30)  NOT NULL,
    [FactEventRow]               BIGINT         IDENTITY (1, 1) NOT NULL
);





