CREATE TABLE [dw].[FactMaterial] (
    [SourceName]                    NVARCHAR (50)  NOT NULL,
    [SourceTime]                    DATETIME       NOT NULL,
    [FactMaterialIsDeleted]         BIT            NOT NULL,
    [FactMaterialHash]              VARBINARY (16) NULL,
    [FactMaterialKey]               BIGINT         NOT NULL,
    [FactRawMaterialKey]            BIGINT         NULL,
    [DimYearKey]                    INT            NOT NULL,
    [DimDateKey]                    INT            NOT NULL,
    [DimShiftKey]                   BIGINT         NULL,
    [DimShiftDefinitionKey]         BIGINT         NULL,
    [DimCrewKey]                    BIGINT         NULL,
    [DimMaterialKey]                BIGINT         NOT NULL,
    [DimRawMaterialKey]             BIGINT         NULL,
    [DimWorkOrderKey]               BIGINT         NULL,
    [DimHeatKey]                    BIGINT         NOT NULL,
    [DimSteelgradeKey]              BIGINT         NULL,
    [DimSteelGroupKey]              BIGINT         NULL,
    [DimMaterialStatusKey]          SMALLINT       NULL,
    [DimCustomerKey]                BIGINT         NULL,
    [DimMaterialCatalogueKey]       BIGINT         NULL,
    [DimProductCatalogueKey]        BIGINT         NULL,
    [DimAssetKeyLastOn]             BIGINT         NULL,
    [DimScrapGroupKey]              BIGINT         NULL,
    [DimTypeOfScrapKey]             SMALLINT       NULL,
    [DimInspectionResultKey]        SMALLINT       NULL,
    [DimAssetKeyMaterialScrap]      BIGINT         NULL,
    [DimDefectCatalogueKeyLastOne]  BIGINT         NULL,
    [DimProductKey]                 BIGINT         NULL,
    [MaterialName]                  NVARCHAR (50)  NOT NULL,
    [RawMaterialName]               NVARCHAR (50)  NULL,
    [MaterialSeqNo]                 SMALLINT       NOT NULL,
    [MaterialCuttingSeq]            SMALLINT       NULL,
    [MaterialChildSeq]              SMALLINT       NULL,
    [MaterialCreated]               DATETIME       NOT NULL,
    [MaterialWeight]                FLOAT (53)     NOT NULL,
    [MaterialThickness]             FLOAT (53)     NOT NULL,
    [MaterialWidth]                 FLOAT (53)     NULL,
    [MaterialLength]                FLOAT (53)     NULL,
    [MaterialCatalogueName]         NVARCHAR (50)  NULL,
    [ProductCatalogueName]          NVARCHAR (50)  NULL,
    [MaterialIsTest]                BIT            NOT NULL,
    [MaterialIsVirtual]             BIT            NULL,
    [MaterialIsReject]              BIT            NOT NULL,
    [MaterialIsScrap]               BIT            NOT NULL,
    [MaterialHeatName]              NVARCHAR (50)  NOT NULL,
    [SteelgradeCode]                NVARCHAR (10)  NULL,
    [SteelgradeName]                NVARCHAR (50)  NULL,
    [SteelGroupCode]                NVARCHAR (10)  NULL,
    [SteelGroupName]                NVARCHAR (50)  NULL,
    [WorkOrderName]                 NVARCHAR (50)  NULL,
    [MaterialLastWeight]            FLOAT (53)     NULL,
    [MaterialLastLength]            FLOAT (53)     NULL,
    [MaterialLastTemperature]       FLOAT (53)     NULL,
    [MaterialLastGrading]           FLOAT (53)     NULL,
    [MaterialSlittingFactor]        SMALLINT       NULL,
    [MaterialScrapPercent]          FLOAT (53)     NOT NULL,
    [MaterialScrapWeight]           FLOAT (53)     NOT NULL,
    [MaterialRejectWeight]          FLOAT (53)     NOT NULL,
    [MaterialScrapRemarks]          NVARCHAR (200) NULL,
    [FurnaceExitTemperature]        FLOAT (53)     NULL,
    [FurnaceHeatingDuration]        INT            NULL,
    [MaterialDefectsNumber]         INT            NOT NULL,
    [MaterialInspectionResult]      VARCHAR (50)   NULL,
    [MaterialStatus]                VARCHAR (50)   NULL,
    [MaterialChargeType]            VARCHAR (50)   NULL,
    [WorkOrderStatus]               VARCHAR (50)   NULL,
    [ProductCreated]                DATETIME       NULL,
    [ProductName]                   NVARCHAR (50)  NULL,
    [ProductWeight]                 FLOAT (53)     NOT NULL,
    [ProductWeightBad]              FLOAT (53)     NOT NULL,
    [MaterialDelayDuration]         BIGINT         NOT NULL,
    [MaterialProductionStart]       DATETIME       NULL,
    [MaterialProductionEnd]         DATETIME       NULL,
    [MaterialProductionDuration]    BIGINT         NULL,
    [RawMaterialProductionStart]    DATETIME       NULL,
    [RawMaterialProductionEnd]      DATETIME       NULL,
    [RawMaterialProductionDuration] BIGINT         NULL,
    [MaterialRollingStart]          DATETIME       NULL,
    [MaterialRollingEnd]            DATETIME       NULL,
    [MaterialRollingDuration]       BIGINT         NULL,
    [MaterialCharged]               DATETIME       NULL,
    [MaterialDischarged]            DATETIME       NULL,
    [ShiftDateWithCode]             NVARCHAR (21)  NOT NULL,
    [CrewName]                      NVARCHAR (50)  NULL,
    [FactMaterialRow]               BIGINT         IDENTITY (1, 1) NOT NULL
);





