CREATE TABLE [dw].[FactRating] (
    [SourceName]             NVARCHAR (50)  NOT NULL,
    [SourceTime]             DATETIME       NOT NULL,
    [FactRatingIsDeleted]    BIT            NOT NULL,
    [FactRatingHash]         VARBINARY (16) NULL,
    [FactRatingKey]          BIGINT         NOT NULL,
    [DimAssetKey]            BIGINT         NULL,
    [DimMaterialKey]         BIGINT         NULL,
    [DimRawMaterialKey]      BIGINT         NULL,
    [DimYearKey]             INT            NULL,
    [DimDateKey]             INT            NOT NULL,
    [RatingRanking]          BIGINT         NULL,
    [RatingValueCurrent]     FLOAT (53)     NULL,
    [RatingValueForced]      FLOAT (53)     NULL,
    [RatingValueAlternative] FLOAT (53)     NULL,
    [RatingValueOriginal]    FLOAT (53)     NULL,
    [MaterialName]           NVARCHAR (50)  NULL,
    [AssetName]              NVARCHAR (50)  NULL,
    [RuleSignal]             NVARCHAR (255) NULL,
    [RuleName]               NVARCHAR (50)  NULL,
    [RatingType]             INT            NULL,
    [RatingGroup]            INT            NULL,
    [RatingCreated]          DATETIME       NOT NULL,
    [RatingModified]         DATETIME       NOT NULL,
    [RatingAlarm]            NVARCHAR (400) NULL,
    [RatingCode]             FLOAT (53)     NULL,
    [FactRatingRow]          BIGINT         IDENTITY (1, 1) NOT NULL
);

