CREATE TABLE [dw].[FactShift] (
    [SourceName]              NVARCHAR (50)   NOT NULL,
    [SourceTime]              DATETIME        NOT NULL,
    [FactShiftIsDeleted]      BIT             NOT NULL,
    [FactShiftHash]           VARBINARY (16)  NULL,
    [FactShiftKey]            BIGINT          NOT NULL,
    [DimYearKey]              INT             NOT NULL,
    [DimDateKey]              INT             NOT NULL,
    [DimYear]                 NVARCHAR (4000) NULL,
    [DimMonth]                NVARCHAR (4000) NULL,
    [DimWeek]                 NVARCHAR (4000) NOT NULL,
    [DimDate]                 NVARCHAR (4000) NULL,
    [DimShiftCode]            NVARCHAR (10)   NOT NULL,
    [DimCrewName]             NVARCHAR (50)   NOT NULL,
    [ShiftDateWithCode]       NVARCHAR (51)   NOT NULL,
    [DefaultStartTime]        TIME (7)        NOT NULL,
    [DefaultEndTime]          TIME (7)        NOT NULL,
    [ShiftStartTime]          DATETIME        NOT NULL,
    [ShiftEndTime]            DATETIME        NOT NULL,
    [ShiftDuration]           INT             NULL,
    [DelayDuration]           BIGINT          NOT NULL,
    [ChargeNumber]            INT             NOT NULL,
    [DischargeNumber]         INT             NOT NULL,
    [UnchargeNumber]          INT             NOT NULL,
    [UndischargeNumber]       INT             NOT NULL,
    [FullScrapNumber]         INT             NOT NULL,
    [PartialScrapNumber]      INT             NOT NULL,
    [RejectNumber]            INT             NOT NULL,
    [ProductCreateNumber]     INT             NOT NULL,
    [WorkOrdersNumber]        INT             NOT NULL,
    [WorkOrdersDuration]      INT             NOT NULL,
    [MaterialsWeight]         FLOAT (53)      NOT NULL,
    [ScrappedMaterialsWeight] FLOAT (53)      NOT NULL,
    [RejectedMaterialsWeight] FLOAT (53)      NOT NULL,
    [ProductsWeight]          FLOAT (53)      NOT NULL,
    [FactShiftRow]            BIGINT          IDENTITY (1, 1) NOT NULL
);

