// THIS CODE WAS GENERATED BY ALARMCREATOR.v2
// DO NOT MODIFY IT MANUALLY - IT SHOULD BE REGENERATED

namespace PE.Common
{
    public class CommonAlarmDefs
    {
        /// <summary>
        ///   Alarm definition for AlarmId: 30623
        ///   MESSAGE FORMAT: Alarm {0} was not found in database: {1}
        ///   PARAMETERS: {Undefined alarm code, Undefined alarm short description}
        /// </summary>
        public const string AlarmCode_UndefinedAlarmCode = "D01";

        /// <summary>
        ///   Alarm definition for AlarmId: 30619
        ///   MESSAGE FORMAT: Module {0} has been started.
        ///   PARAMETERS: {Started module name}
        /// </summary>
        public const string AlarmCode_ModuleHasBeenStarted = "M01";

        /// <summary>
        ///   Alarm definition for AlarmId: 30620
        ///   MESSAGE FORMAT: Module {0} has been stopped.
        ///   PARAMETERS: {Stopped module name}
        /// </summary>
        public const string AlarmCode_ModuleHasBeenStopped = "M02";

        /// <summary>
        ///   Alarm definition for AlarmId: 30621
        ///   MESSAGE FORMAT: Module {0} is alive.
        ///   PARAMETERS: {Alive module name}
        /// </summary>
        public const string AlarmCode_ModuleIsAlive = "M03";

        /// <summary>
        ///   Alarm definition for AlarmId: 30622
        ///   MESSAGE FORMAT: Module {0} has been initialized.
        ///   PARAMETERS: {Module name}
        /// </summary>
        public const string AlarmCode_ModuleHasBeenInitialized = "M04";

        /// <summary>
        ///   Alarm definition for AlarmId: 30624
        ///   MESSAGE FORMAT: New record processed. Table {0}
        ///   PARAMETERS: {TableName}
        /// </summary>
        public const string AlarmCode_NewRecordProcessed = "PMT01";

        /// <summary>
        ///   Alarm definition for AlarmId: 30626
        ///   MESSAGE FORMAT: Error in processing external data.  Table {0}
        ///   PARAMETERS: {TableName}
        /// </summary>
        public const string AlarmCode_ErrorInExternalDBRecord = "PMT02";

        /// <summary>
        ///   Alarm definition for AlarmId: 30627
        ///   MESSAGE FORMAT: Error in processing external data. Table {0}
        ///   PARAMETERS: {tablename}
        /// </summary>
        public const string AlarmCode_ErrorInProcessingExternalData = "PMT03";

        /// <summary>
        ///   Alarm definition for AlarmId: 30628
        ///   MESSAGE FORMAT: Max attempts of external data reading reached.  Table {0}
        ///   PARAMETERS: {TableName}
        /// </summary>
        public const string AlarmCode_MaxAttemptsReached = "PMT04";

        /// <summary>
        ///   Alarm definition for AlarmId: 30629
        ///   MESSAGE FORMAT: Oracle selection command is empty.  Table {0}
        ///   PARAMETERS: {Nazwa tabeli}
        /// </summary>
        public const string AlarmCode_OracleSelectionCommandIsEmpty = "PMT05";

        /// <summary>
        ///   Alarm definition for AlarmId: 30630
        ///   MESSAGE FORMAT: External Oracle DB connection Error.  Table {0}
        ///   PARAMETERS: {Nazwa tabeli}
        /// </summary>
        public const string AlarmCode_ExternalOracleDBConnectionError = "PMT06";

        /// <summary>
        ///   Alarm definition for AlarmId: 30631
        ///   MESSAGE FORMAT: Reset processing status in external DB row
        /// </summary>
        public const string AlarmCode_ResetProcessingStatusInExternalDBRow = "PMT07";

        /// <summary>
        ///   Alarm definition for AlarmId: 30633
        ///   MESSAGE FORMAT: Set missed status in external table processing for row.
        /// </summary>
        public const string AlarmCode_SetMissedStatusInExternalTableProcessingForRow = "PMT08";

        /// <summary>
        ///   Alarm definition for AlarmId: 30606
        ///   MESSAGE FORMAT: Limit '{0}' was not found
        ///   PARAMETERS: {limitName}
        /// </summary>
        public const string AlarmCode_RequestedLimitNotFound = "S001";

        /// <summary>
        ///   Alarm definition for AlarmId: 30607
        ///   MESSAGE FORMAT: Parameter '{0}' not found
        ///   PARAMETERS: {paramName}
        /// </summary>
        public const string AlarmCode_ParameterNotFound = "S002";

        /// <summary>
        ///   Alarm definition for AlarmId: 30608
        ///   MESSAGE FORMAT: DB operation failed. Error during processing of function '{0}'
        ///   PARAMETERS: {functionName}
        /// </summary>
        public const string AlarmCode_DBOperationFailed = "S003";

        /// <summary>
        ///   Alarm definition for AlarmId: 30610
        ///   MESSAGE FORMAT: Module {0} changed its state to {1}
        ///   PARAMETERS: {module, state}
        /// </summary>
        public const string AlarmCode_ModuleChangedItsState = "S004";

        /// <summary>
        ///   Alarm definition for AlarmId: 30611
        ///   MESSAGE FORMAT: DB connection status: {0}
        ///   PARAMETERS: {state}
        /// </summary>
        public const string AlarmCode_DBConnectionChangedItsState = "S005";

        /// <summary>
        ///   Alarm definition for AlarmId: 30612
        ///   MESSAGE FORMAT: L1 link (TCP) status: {0}
        ///   PARAMETERS: {state}
        /// </summary>
        public const string AlarmCode_L1LinkTCPStatus = "S006";

        /// <summary>
        ///   Alarm definition for AlarmId: 30613
        ///   MESSAGE FORMAT: L1 link status (OPC): {0}
        ///   PARAMETERS: {state}
        /// </summary>
        public const string AlarmCode_L1LinkOPCStatus = "S007";

        /// <summary>
        ///   Alarm definition for AlarmId: 30614
        ///   MESSAGE FORMAT: DB connection status: {0}
        ///   PARAMETERS: {state}
        /// </summary>
        public const string AlarmCode_ExternalDBConnectionChangedItsState = "S008";

        /// <summary>
        ///   Alarm definition for AlarmId: 30615
        ///   MESSAGE FORMAT: User {0} logged in
        ///   PARAMETERS: {user}
        /// </summary>
        public const string AlarmCode_UserLoggedIn = "S009";

        /// <summary>
        ///   Alarm definition for AlarmId: 30616
        ///   MESSAGE FORMAT: Cannot generate new shift calendar records because prevoius shifts not exist.
        /// </summary>
        public const string AlarmCode_CannotGenerateNewShiftCalendarRecordsBecausePrevoiusShiftsNotExist = "S010";

        /// <summary>
        ///   Alarm definition for AlarmId: 30618
        ///   MESSAGE FORMAT: Cannot generate new shift calendar records because next shifts exist.
        /// </summary>
        public const string AlarmCode_CannotGenerateNewShiftCalendarRecordsBecauseNextShiftsExist = "S011";

        /// <summary>
        ///   Alarm definition for AlarmId: 30634
        ///   MESSAGE FORMAT: Break exists in previous week. New elements in shift calendar added with gaps. {0}
        ///   PARAMETERS: {param}
        /// </summary>
        public const string AlarmCode_BreakExistsInPreviousWeekNewElementsInShiftCalendarAddedWithGaps = "S012";

        /// <summary>
        ///   Alarm definition for AlarmId: 30635
        ///   MESSAGE FORMAT: Exception in view bag method: {0}. Exception message: {1}
        ///   PARAMETERS: {methodName, exMessage}
        /// </summary>
        public const string AlarmCode_ExceptionInViewBagMethod = "S014";

        /// <summary>
        ///   Alarm definition for AlarmId: 30637
        ///   MESSAGE FORMAT: Invalid paramteter in module {0}, parameter '{1}', description '{2}'.
        ///   PARAMETERS: {module, parameter, description}
        /// </summary>
        public const string AlarmCode_InvalidParameter = "S015";

        /// <summary>
        ///   Alarm definition for AlarmId: 40696
        ///   MESSAGE FORMAT: Module {0} communication timeout
        ///   PARAMETERS: {Module name}
        /// </summary>
        public const string AlarmCode_ModuleCommunicationTimeout = "S016";

        /// <summary>
        ///   Alarm definition for AlarmId: 40697
        ///   MESSAGE FORMAT: Internal module {0} error
        ///   PARAMETERS: {module name}
        /// </summary>
        public const string AlarmCode_InternalModuleError = "S017";

        /// <summary>
        ///   Alarm definition for AlarmId: 40821
        ///   MESSAGE FORMAT: Module {0} is not available
        ///   PARAMETERS: {module name}
        /// </summary>
        public const string AlarmCode_ModuleNotAvailable = "S018";
    }
}
