// THIS CODE WAS GENERATED BY ALARMCREATOR.v3
// DO NOT MODIFY IT MANUALLY - IT SHOULD BE REGENERATED

namespace PE.Common
{
  public static class ModuleAlarmDefsBase
  {
    /// <summary>
    /// Alarm definition for AlarmId: 50
    /// FORMAT: Error during processing work order transfer table.
    /// </summary>
    public const string AlarmCode_TransferDataFromTransferTableToAdapter = "DBA001";

    /// <summary>
    /// Alarm definition for AlarmId: 248
    /// FORMAT: Violation of existing reference.
    /// </summary>
    public const string AlarmCode_DataBaseAdapterExistingReferenceViolation = "DBA002";

    /// <summary>
    /// Alarm definition for AlarmId: 249
    /// FORMAT: Record is not found.
    /// </summary>
    public const string AlarmCode_DataBaseAdapterRecordNotFound = "DBA003";

    /// <summary>
    /// Alarm definition for AlarmId: 250
    /// FORMAT: Record is not unique.
    /// </summary>
    public const string AlarmCode_DataBaseAdapterRecordNotUnique = "DBA004";

    /// <summary>
    /// Alarm definition for AlarmId: 251
    /// FORMAT: Operation not finished due to unexpected error.
    /// </summary>
    public const string AlarmCode_DataBaseAdapterUnexpectedError = "DBA005";

    /// <summary>
    /// Alarm definition for AlarmId: 51
    /// FORMAT: Timeout during work order transfer table processing.
    /// </summary>
    public const string AlarmCode_TimeoutDuringProcessingWorkOrderTransferTable = "DBA006";

    /// <summary>
    /// Alarm definition for AlarmId: 117
    /// FORMAT: Error while updating work order definition.
    /// </summary>
    public const string AlarmCode_WorkOrderDefinitionUpdateError = "DBA007";

    /// <summary>
    /// Alarm definition for AlarmId: 116
    /// FORMAT: Work order definition {0} status prevents update.
    /// PARAMS: @0: WorkOrderName
    /// </summary>
    public const string AlarmCode_WorkOrderDefinitionNotUpdatable = "DBA008";

    /// <summary>
    /// Alarm definition for AlarmId: 114
    /// FORMAT: Can not remove already processed work order definition.
    /// </summary>
    public const string AlarmCode_WorkOrderDefinitionAlreadyProcessed = "DBA009";

    /// <summary>
    /// Alarm definition for AlarmId: 115
    /// FORMAT: Error while removing work order definition.
    /// </summary>
    public const string AlarmCode_WorkOrderDefinitionDeleteError = "DBA010";

    /// <summary>
    /// Alarm definition for AlarmId: 252
    /// FORMAT: Error while resetting work order report.
    /// </summary>
    public const string AlarmCode_WorkOrderReportNotResetted = "DBA011";

    /// <summary>
    /// Alarm definition for AlarmId: 411
    /// FORMAT: Work order report not sent due to unexpected error.
    /// </summary>
    public const string AlarmCode_WorkOrderReportNotSent = "DBA012";

    /// <summary>
    /// Alarm definition for AlarmId: 412
    /// FORMAT: Coil report not sent due to unexpected error.
    /// </summary>
    public const string AlarmCode_CoilReportNotSent = "DBA013";

    /// <summary>
    /// Alarm definition for AlarmId: 413
    /// FORMAT: Error while resetting work order report.
    /// PARAMS: @0: productName
    /// </summary>
    public const string AlarmCode_ProductReportNotResetted = "DBA014";

    /// <summary>
    /// Alarm definition for AlarmId: 10430
    /// FORMAT: Product {0} report not sent due to unexpected error.
    /// PARAMS: @0: productName
    /// </summary>
    public const string AlarmCode_ProductReportNotSent = "DBA015";

    /// <summary>
    /// Alarm definition for AlarmId: 168
    /// FORMAT: Error while initializing {0} device. {1}
    /// PARAMS: @0: GaugeName, @1: Gauge Name, @2: Message, @3: Message
    /// </summary>
    public const string AlarmCode_DVCGaugeInitializeError = "DVC001";

    /// <summary>
    /// Alarm definition for AlarmId: 169
    /// FORMAT: Error while starting {0} device. {1}
    /// PARAMS: @0: Gauge Name, @1: Gauge Name, @2: Message, @3: Message
    /// </summary>
    public const string AlarmCode_DVCGaugeStartError = "DVC002";

    /// <summary>
    /// Alarm definition for AlarmId: 170
    /// FORMAT: Error while executing timer method for {0} device. {1}
    /// PARAMS: @0: Gauge Name, @1: Message, @2: Gauge Name, @3: Message
    /// </summary>
    public const string AlarmCode_DVCGaugeTimerMethodError = "DVC003";

    /// <summary>
    /// Alarm definition for AlarmId: 171
    /// FORMAT: Error while stopping {0} device. {1}
    /// PARAMS: @0: Gauge Name, @1: Gauge Name, @2: Message, @3: Message
    /// </summary>
    public const string AlarmCode_DVCGaugeStopError = "DVC004";

    /// <summary>
    /// Alarm definition for AlarmId: 172
    /// FORMAT: Error while starting SIAS device. {0}
    /// PARAMS: @0: Message, @1: Message
    /// </summary>
    public const string AlarmCode_DVCSIASStartError = "DVC006";

    /// <summary>
    /// Alarm definition for AlarmId: 173
    /// FORMAT: Error while stoping SIAS device. {0}
    /// PARAMS: @0: Message, @1: Message
    /// </summary>
    public const string AlarmCode_DVCSIASStopError = "DVC007";

    /// <summary>
    /// Alarm definition for AlarmId: 174
    /// FORMAT: Error while starting Label Printer device. {0}
    /// PARAMS: @0: Message, @1: Message
    /// </summary>
    public const string AlarmCode_DVCLabelPrinterStartError = "DVC008";

    /// <summary>
    /// Alarm definition for AlarmId: 198
    /// FORMAT: No data from Heat Id Reader for material {0}
    /// PARAMS: @0: RawMaterialId
    /// </summary>
    public const string AlarmCode_DVCHeatReaderNoData = "DVC009";

    /// <summary>
    /// Alarm definition for AlarmId: 199
    /// FORMAT: Invalid data from Heat Id Reader for material {0}
    /// PARAMS: @0: RawMaterialId
    /// </summary>
    public const string AlarmCode_DVCHeatReaderInvalid = "DVC010";

    /// <summary>
    /// Alarm definition for AlarmId: 119
    /// FORMAT: For Equipment: {0} actual weight: {1} is going to be over total weight: {2}
    /// PARAMS: @0: equimentName, @1: actualWeight, @2: totalWeight
    /// </summary>
    public const string AlarmCode_EquipmentWeightWarning = "EQT001";

    /// <summary>
    /// Alarm definition for AlarmId: 120
    /// FORMAT: For equipment: {0}, actual weight: {1} is more than total weight: {2}
    /// PARAMS: @0: equipmentName, @1: actualWeight, @2: totalWeight
    /// </summary>
    public const string AlarmCode_EquipmentWeightError = "EQT002";

    /// <summary>
    /// Alarm definition for AlarmId: 121
    /// FORMAT: For equipment: {0}, actual weight: {1} is more than total weight: {2}
    /// PARAMS: @0: equipmentName, @1: actualWeight, @2: totalWeight
    /// </summary>
    public const string AlarmCode_EquipmentWeightErrorWithPopup = "EQT003";

    /// <summary>
    /// Alarm definition for AlarmId: 122
    /// FORMAT: For equipment: {0}, planned service date: {1} is overdue.
    /// PARAMS: @0: equipmentName, @1: plannedServiceDate
    /// </summary>
    public const string AlarmCode_EquipmentServiceDateError = "EQT004";

    /// <summary>
    /// Alarm definition for AlarmId: 123
    /// FORMAT: For equipment: {0}, planned service date: {1} is overdue.
    /// PARAMS: @0: equipmentName, @1: plannedServiceDate
    /// </summary>
    public const string AlarmCode_EquipmentServiceDateErrorWithPopup = "EQT005";

    /// <summary>
    /// Alarm definition for AlarmId: 124
    /// FORMAT: For equipment: {0}, actual weight: {1} is more than total weight: {2} and planned service date: {3} is overdue
    /// PARAMS: @0: equipmentName, @1: actualWeight, @2: totalWeight, @3: plannedServiceDate
    /// </summary>
    public const string AlarmCode_EquipmentWeightAndServiceDateError = "EQT006";

    /// <summary>
    /// Alarm definition for AlarmId: 125
    /// FORMAT: For equipment: {0}, actual weight: {1} is more than total weight: {2} and planned service date: {3} is overdue
    /// PARAMS: @0: equipmentName, @1: actualWeight, @2: totalWeight, @3: plannedServiceDate
    /// </summary>
    public const string AlarmCode_EquipmentWeightAndServiceDateErrorWithPopup = "EQT007";

    /// <summary>
    /// Alarm definition for AlarmId: 231
    /// FORMAT: Violation of existing reference.
    /// </summary>
    public const string AlarmCode_EventsExistingReferenceViolation = "EVT001";

    /// <summary>
    /// Alarm definition for AlarmId: 232
    /// FORMAT: Record is not found.
    /// </summary>
    public const string AlarmCode_EventsRecordNotFound = "EVT002";

    /// <summary>
    /// Alarm definition for AlarmId: 233
    /// FORMAT: Record is not unique.
    /// </summary>
    public const string AlarmCode_EventsRecordNotUnique = "EVT003";

    /// <summary>
    /// Alarm definition for AlarmId: 240
    /// FORMAT: Operation not finished due to unexpected error.
    /// </summary>
    public const string AlarmCode_EventsUnexpectedError = "EVT004";

    /// <summary>
    /// Alarm definition for AlarmId: 75
    /// FORMAT: Delay start date {0} is not before end date {1}.
    /// PARAMS: @0: DelayStart, @1: DelayEnd
    /// </summary>
    public const string AlarmCode_InvalidDelayDates = "EVT005";

    /// <summary>
    /// Alarm definition for AlarmId: 243
    /// FORMAT: Invalid operation.
    /// </summary>
    public const string AlarmCode_InvalidOperation = "EVT006";

    /// <summary>
    /// Alarm definition for AlarmId: 244
    /// FORMAT: Could not override delay end time from {0} to null in case if already ended.
    /// PARAMS: @0: DelayEnd
    /// </summary>
    public const string AlarmCode_CannotSetDelayEndToNull = "EVT007";

    /// <summary>
    /// Alarm definition for AlarmId: 152
    /// FORMAT: Delay category with code {0} already exists in DB.
    /// PARAMS: @0: categoryCode
    /// </summary>
    public const string AlarmCode_DelayCategoryExists = "EVT008";

    /// <summary>
    /// Alarm definition for AlarmId: 159
    /// FORMAT: Delay group {0} already exists.
    /// PARAMS: @0: groupCode
    /// </summary>
    public const string AlarmCode_DelayGroupExists = "EVT009";

    /// <summary>
    /// Alarm definition for AlarmId: 246
    /// FORMAT: Delay catalogue {0} exists.
    /// PARAMS: @0: catalogueCode
    /// </summary>
    public const string AlarmCode_DelayCatalogueExists = "EVT010";

    /// <summary>
    /// Alarm definition for AlarmId: 407
    /// FORMAT: Default catalogue not found for event type
    /// </summary>
    public const string AlarmCode_DefaultEventCatalogueNotFound = "EVT011";

    /// <summary>
    /// Alarm definition for AlarmId: 322
    /// FORMAT: Unexpected error while sending message to L1.
    /// </summary>
    public const string AlarmCode_MessageToL1NotSent = "L1A001";

    /// <summary>
    /// Alarm definition for AlarmId: 324
    /// FORMAT: Cannot init connection with OPC server with address {0}.
    /// PARAMS: @0: serverAddress
    /// </summary>
    public const string AlarmCode_CannotInitConnectionWithOPCServer = "L1A002";

    /// <summary>
    /// Alarm definition for AlarmId: 325
    /// FORMAT: Connection with OPC server {0} initialized.
    /// PARAMS: @0: serverAddress
    /// </summary>
    public const string AlarmCode_ConnectionWithOPCServerInitialized = "L1A003";

    /// <summary>
    /// Alarm definition for AlarmId: 326
    /// FORMAT: Connection with OPC server {0} started.
    /// PARAMS: @0: serverAddress
    /// </summary>
    public const string AlarmCode_ConnectionWithOPCServerStarted = "L1A004";

    /// <summary>
    /// Alarm definition for AlarmId: 327
    /// FORMAT: Connection with OPC server {0} not started.
    /// PARAMS: @0: serverAddress
    /// </summary>
    public const string AlarmCode_CannotStartConnectionWithOPCServer = "L1A005";

    /// <summary>
    /// Alarm definition for AlarmId: 328
    /// FORMAT: Unexpected error while getting subscription for OPC server {0}.
    /// PARAMS: @0: serverAddress
    /// </summary>
    public const string AlarmCode_CannotGetSubscriptionForOPCServer = "L1A006";

    /// <summary>
    /// Alarm definition for AlarmId: 329
    /// FORMAT: Cannot read actual tag values because module L1Adapter is not yet initialized.
    /// </summary>
    public const string AlarmCode_CannotReadL1TagsBecauseModuleIsNotInitialized = "L1A007";

    /// <summary>
    /// Alarm definition for AlarmId: 330
    /// FORMAT: Operation not finished due to unexpected error.
    /// </summary>
    public const string AlarmCode_L1AdapterUnexpectedError = "L1A008";

    /// <summary>
    /// Alarm definition for AlarmId: 331
    /// FORMAT: Unexpected exception while processing measurement for point with code {0}.
    /// PARAMS: @0: assetCode
    /// </summary>
    public const string AlarmCode_ErrorDuringProcessingMeasurement = "L1A009";

    /// <summary>
    /// Alarm definition for AlarmId: 332
    /// FORMAT: Cannot find measurements for point with code {0}.
    /// PARAMS: @0: featureCode
    /// </summary>
    public const string AlarmCode_MeasurementsNotFoundForPoint = "L1A010";

    /// <summary>
    /// Alarm definition for AlarmId: 333
    /// FORMAT: Record is not found.
    /// </summary>
    public const string AlarmCode_L1AdapterRecordNotFound = "L1A011";

    /// <summary>
    /// Alarm definition for AlarmId: 334
    /// FORMAT: Record is not unique.
    /// </summary>
    public const string AlarmCode_L1AdapterRecordNotUnique = "L1A012";

    /// <summary>
    /// Alarm definition for AlarmId: 335
    /// FORMAT: Violation of existing reference.
    /// </summary>
    public const string AlarmCode_L1AdapterExistingReferenceViolation = "L1A013";

    /// <summary>
    /// Alarm definition for AlarmId: 92
    /// FORMAT: Equipment group with code {0} already exists
    /// PARAMS: @0: code
    /// </summary>
    public const string AlarmCode_EqGrpCodeNotUnique = "MNT001";

    /// <summary>
    /// Alarm definition for AlarmId: 93
    /// FORMAT: Equipment group with code {0} has been created
    /// PARAMS: @0: code
    /// </summary>
    public const string AlarmCode_EqGrpCreated = "MNT002";

    /// <summary>
    /// Alarm definition for AlarmId: 94
    /// FORMAT: Equipment group with code {0} has been updated
    /// PARAMS: @0: code
    /// </summary>
    public const string AlarmCode_EqGrpUpdated = "MNT003";

    /// <summary>
    /// Alarm definition for AlarmId: 95
    /// FORMAT: Equipment group with code {0} has been deleted
    /// PARAMS: @0: code
    /// </summary>
    public const string AlarmCode_EqGrpDeleted = "MNT004";

    /// <summary>
    /// Alarm definition for AlarmId: 96
    /// FORMAT: Error occured in module: {0}
    /// PARAMS: @0: errorDesc
    /// </summary>
    public const string AlarmCode_EqGrpGeneralError = "MNT005";

    /// <summary>
    /// Alarm definition for AlarmId: 97
    /// FORMAT: Equipment element {0} has been created
    /// PARAMS: @0: element
    /// </summary>
    public const string AlarmCode_EqElementCreated = "MNT006";

    /// <summary>
    /// Alarm definition for AlarmId: 98
    /// FORMAT: Equipment element {0} changed status to {1}
    /// PARAMS: @0: element, @1: status
    /// </summary>
    public const string AlarmCode_EqElementChangedStatus = "MNT007";

    /// <summary>
    /// Alarm definition for AlarmId: 99
    /// FORMAT: Equipment element {0} has been updated
    /// PARAMS: @0: element
    /// </summary>
    public const string AlarmCode_EqElementUpdated = "MNT008";

    /// <summary>
    /// Alarm definition for AlarmId: 100
    /// FORMAT: Error occured in module: {0}
    /// PARAMS: @0: errorDesc
    /// </summary>
    public const string AlarmCode_EqElementGeneralError = "MNT009";

    /// <summary>
    /// Alarm definition for AlarmId: 101
    /// FORMAT: Equipment group with code {0) can not be deleted because there is equipment assigned
    /// PARAMS: @0: element
    /// </summary>
    public const string AlarmCode_EqGrpDeleteNotPossible = "MNT010";

    /// <summary>
    /// Alarm definition for AlarmId: 102
    /// FORMAT: Equipment element {0} has been deleted
    /// PARAMS: @0: element
    /// </summary>
    public const string AlarmCode_EqElementDeleted = "MNT011";

    /// <summary>
    /// Alarm definition for AlarmId: 10415
    /// FORMAT: Record is not unique.
    /// </summary>
    public const string AlarmCode_MaintenanceRecordNotUnique = "MNT012";

    /// <summary>
    /// Alarm definition for AlarmId: 10416
    /// FORMAT: Violation of existing reference.
    /// </summary>
    public const string AlarmCode_MaintenanceExistingReferenceViolation = "MNT013";

    /// <summary>
    /// Alarm definition for AlarmId: 10417
    /// FORMAT: Record is not found.
    /// </summary>
    public const string AlarmCode_MaintenanceRecordNotFound = "MNT014";

    /// <summary>
    /// Alarm definition for AlarmId: 10418
    /// FORMAT: Operation not finished due to unexpected error.
    /// </summary>
    public const string AlarmCode_MaintenanceUnexpectedError = "MNT015";

    /// <summary>
    /// Alarm definition for AlarmId: 10419
    /// FORMAT: All equipment elements being in operation are updated with processed weight of {0} kg.
    /// PARAMS: @0: materialWeight
    /// </summary>
    public const string AlarmCode_EquipmentUpdatedByMaterialWeight = "MNT016";

    /// <summary>
    /// Alarm definition for AlarmId: 10420
    /// FORMAT: Error while updating equipment in operation by processed weight {0} kg.
    /// PARAMS: @0: materialWeight
    /// </summary>
    public const string AlarmCode_ErrorUpdatingEquipmentByWeight = "MNT017";

    /// <summary>
    /// Alarm definition for AlarmId: 336
    /// FORMAT: Violation of existing reference.
    /// </summary>
    public const string AlarmCode_MeasurementsValueArchiveExistingReferenceViolation = "MVH001";

    /// <summary>
    /// Alarm definition for AlarmId: 337
    /// FORMAT: Record is not found.
    /// </summary>
    public const string AlarmCode_MeasurementsValueArchiveRecordNotFound = "MVH002";

    /// <summary>
    /// Alarm definition for AlarmId: 338
    /// FORMAT: Record is not unique.
    /// </summary>
    public const string AlarmCode_MeasurementsValueArchiveRecordNotUnique = "MVH003";

    /// <summary>
    /// Alarm definition for AlarmId: 339
    /// FORMAT: Operation not finished due to unexpected error.
    /// </summary>
    public const string AlarmCode_MeasurementsValueArchiveUnexpectedError = "MVH004";

    /// <summary>
    /// Alarm definition for AlarmId: 340
    /// FORMAT: Unexpected exception while getting measurement for feature with code {0}.
    /// PARAMS: @0: featureCode
    /// </summary>
    public const string AlarmCode_CannotGetMeasurements = "MVH005";

    /// <summary>
    /// Alarm definition for AlarmId: 34
    /// FORMAT: Critical error when adding work order [id:{0}] to schedule
    /// PARAMS: @0: WorkOrderId
    /// </summary>
    public const string AlarmCode_WorkOrderNotAddedToSchedule = "PPL001";

    /// <summary>
    /// Alarm definition for AlarmId: 35
    /// FORMAT: Critical error when adding work order to schedule.
    /// </summary>
    public const string AlarmCode_ToManyItemsInSchedule = "PPL002";

    /// <summary>
    /// Alarm definition for AlarmId: 36
    /// FORMAT: Critical error when deleting item from schedule.
    /// </summary>
    public const string AlarmCode_DeleteItemFromSchedule = "PPL003";

    /// <summary>
    /// Alarm definition for AlarmId: 37
    /// FORMAT: Warning - can't swap items. No item to change position near position {0}
    /// PARAMS: @0: scheduleItem.OrderSeq
    /// </summary>
    public const string AlarmCode_NoItemToSwap = "PPL004";

    /// <summary>
    /// Alarm definition for AlarmId: 38
    /// FORMAT: Critical error appears while test work order was beeing saved into DB - changes not saved
    /// </summary>
    public const string AlarmCode_PPLSavingError = "PPL005";

    /// <summary>
    /// Alarm definition for AlarmId: 39
    /// FORMAT: Error during processing create test work order function - unexpected error may happend
    /// </summary>
    public const string AlarmCode_CreateTestWorkOrder = "PPL006";

    /// <summary>
    /// Alarm definition for AlarmId: 40
    /// FORMAT: Given number of materials in impropper
    /// </summary>
    public const string AlarmCode_ImproperNumberOfMaterials = "PPL007";

    /// <summary>
    /// Alarm definition for AlarmId: 56
    /// FORMAT: Schedule may be empty.
    /// </summary>
    public const string AlarmCode_EmptySchedule = "PPL008";

    /// <summary>
    /// Alarm definition for AlarmId: 57
    /// FORMAT: Request about next material in schedule thrown unexpected error.
    /// </summary>
    public const string AlarmCode_RequestFirstMaterialInProductionSchedule = "PPL009";

    /// <summary>
    /// Alarm definition for AlarmId: 72
    /// FORMAT: Error during moving items in schedule form position {0} to position {1}.
    /// PARAMS: @0: oldPosition, @1: newPosition
    /// </summary>
    public const string AlarmCode_MoveItemInScheduleError = "PPL010";

    /// <summary>
    /// Alarm definition for AlarmId: 262
    /// FORMAT: Record is not unique.
    /// </summary>
    public const string AlarmCode_ProdPlaningRecordNotUnique = "PPL011";

    /// <summary>
    /// Alarm definition for AlarmId: 263
    /// FORMAT: Violation of existing reference.
    /// </summary>
    public const string AlarmCode_ProdPlaningExistingReferenceViolation = "PPL012";

    /// <summary>
    /// Alarm definition for AlarmId: 264
    /// FORMAT: Record is not found.
    /// </summary>
    public const string AlarmCode_ProdPlaningRecordNotFound = "PPL013";

    /// <summary>
    /// Alarm definition for AlarmId: 265
    /// FORMAT: Operation not finished due to unexpected error.
    /// </summary>
    public const string AlarmCode_ProdPlaningUnexpectedError = "PPL014";

    /// <summary>
    /// Alarm definition for AlarmId: 341
    /// FORMAT: Something went wrong while calculating KPI for work order.
    /// </summary>
    public const string AlarmCode_KPIForWorkOrderNotCalculated = "PRF001";

    /// <summary>
    /// Alarm definition for AlarmId: 342
    /// FORMAT: Violation of existing reference.
    /// </summary>
    public const string AlarmCode_PerformanceExistingReferenceViolation = "PRF002";

    /// <summary>
    /// Alarm definition for AlarmId: 343
    /// FORMAT: Record is not found.
    /// </summary>
    public const string AlarmCode_PerformanceRecordNotFound = "PRF003";

    /// <summary>
    /// Alarm definition for AlarmId: 344
    /// FORMAT: Record is not unique.
    /// </summary>
    public const string AlarmCode_PerformanceRecordNotUnique = "PRF004";

    /// <summary>
    /// Alarm definition for AlarmId: 345
    /// FORMAT: Operation not finished due to unexpected error.
    /// </summary>
    public const string AlarmCode_PerformanceUnexpectedError = "PRF005";

    /// <summary>
    /// Alarm definition for AlarmId: 346
    /// FORMAT: Something went wrong while calculating timer KPIs.
    /// </summary>
    public const string AlarmCode_TimerKPIsNotCalculated = "PRF006";

    /// <summary>
    /// Alarm definition for AlarmId: 347
    /// FORMAT: Something went wrong while calculating timer KPIs.
    /// </summary>
    public const string AlarmCode_ShiftKPIsNotCalculated = "PRF007";

    /// <summary>
    /// Alarm definition for AlarmId: 348
    /// FORMAT: Something went wrong while calculating metallic yield KPIs.
    /// </summary>
    public const string AlarmCode_MetallicYieldKPINotCalculated = "PRF008";

    /// <summary>
    /// Alarm definition for AlarmId: 349
    /// FORMAT: Something went wrong while calculating quality yield KPI.
    /// </summary>
    public const string AlarmCode_QualityYieldKPINotCalculated = "PRF009";

    /// <summary>
    /// Alarm definition for AlarmId: 350
    /// FORMAT: Something went wrong while calculating meantime of day KPI.
    /// </summary>
    public const string AlarmCode_MeanTimeOfDayKPINotCalculated = "PRF010";

    /// <summary>
    /// Alarm definition for AlarmId: 351
    /// FORMAT: Something went wrong while calculating OEE KPI.
    /// </summary>
    public const string AlarmCode_OEEKPINotCalculated = "PRF011";

    /// <summary>
    /// Alarm definition for AlarmId: 352
    /// FORMAT: Something went wrong while calculating test time percentage KPI.
    /// </summary>
    public const string AlarmCode_TestTimePercentageKPINotCalculated = "PRF012";

    /// <summary>
    /// Alarm definition for AlarmId: 353
    /// FORMAT: Something went wrong while calculating production plan variance KPI.
    /// </summary>
    public const string AlarmCode_ProductionPlanVarianceKPINotCalculated = "PRF013";

    /// <summary>
    /// Alarm definition for AlarmId: 354
    /// FORMAT: Something went wrong while calculating scrap percentage KPI.
    /// </summary>
    public const string AlarmCode_ScrapPercentageKPINotCalculated = "PRF014";

    /// <summary>
    /// Alarm definition for AlarmId: 28
    /// FORMAT: Work order {0} status does not allow it to update.
    /// PARAMS: @0: WorkOrderName
    /// </summary>
    public const string AlarmCode_WorkOrderNotUpdatable = "PRM001";

    /// <summary>
    /// Alarm definition for AlarmId: 201
    /// FORMAT: Critical error when creating heat
    /// </summary>
    public const string AlarmCode_HeatNotCreated = "PRM0012";

    /// <summary>
    /// Alarm definition for AlarmId: 202
    /// FORMAT: Error while removing work order {0}.
    /// PARAMS: @0: workOrderName
    /// </summary>
    public const string AlarmCode_WorkOrderNotDeleted = "PRM0013";

    /// <summary>
    /// Alarm definition for AlarmId: 203
    /// FORMAT: Steelgrade {0} already exists.
    /// PARAMS: @0: steelgradeCode
    /// </summary>
    public const string AlarmCode_SteelgradeAlreadyExists = "PRM0014";

    /// <summary>
    /// Alarm definition for AlarmId: 204
    /// FORMAT: Material catalogue {0} already exists.
    /// PARAMS: @0: materialCatalogueName
    /// </summary>
    public const string AlarmCode_MaterialCatalogueAlreadyExists = "PRM0015";

    /// <summary>
    /// Alarm definition for AlarmId: 205
    /// FORMAT: Product catalogue {0} already exist.
    /// PARAMS: @0: productCatalogueName
    /// </summary>
    public const string AlarmCode_ProductCatalogueAlreadyExists = "PRM0016";

    /// <summary>
    /// Alarm definition for AlarmId: 156
    /// FORMAT: Scrap group {0} already exists.
    /// PARAMS: @0: scrapGroupName
    /// </summary>
    public const string AlarmCode_ScrapGroupAlreadyExists = "PRM0017";

    /// <summary>
    /// Alarm definition for AlarmId: 29
    /// FORMAT: Critical error when creating work order {0}.
    /// PARAMS: @0: WorkOrderName
    /// </summary>
    public const string AlarmCode_WorkOrderNotCreated = "PRM002";

    /// <summary>
    /// Alarm definition for AlarmId: 30
    /// FORMAT: Error while updating steelgrade {0}.
    /// PARAMS: @0: steelgradeCode
    /// </summary>
    public const string AlarmCode_SteelgradeUpdate = "PRM003";

    /// <summary>
    /// Alarm definition for AlarmId: 31
    /// FORMAT: Error while updating material catalogue {0}.
    /// PARAMS: @0: materialCatalogueName
    /// </summary>
    public const string AlarmCode_MaterialCatalogueUpdate = "PRM004";

    /// <summary>
    /// Alarm definition for AlarmId: 32
    /// FORMAT: Error while updating product catalogue {0}.
    /// PARAMS: @0: productCatalogueName
    /// </summary>
    public const string AlarmCode_ProductCatalogueUpdate = "PRM005";

    /// <summary>
    /// Alarm definition for AlarmId: 33
    /// FORMAT: Product catalogue could not be found
    /// </summary>
    public const string AlarmCode_ProductCatalogueNotFound = "PRM006";

    /// <summary>
    /// Alarm definition for AlarmId: 54
    /// FORMAT: Searching first not connected material in schedule thrown unexpected error
    /// </summary>
    public const string AlarmCode_FindFirstFreeScheduledMaterial = "PRM009";

    /// <summary>
    /// Alarm definition for AlarmId: 60
    /// FORMAT: Critical error when creating product.
    /// </summary>
    public const string AlarmCode_ProductCreationFailed = "PRM011";

    /// <summary>
    /// Alarm definition for AlarmId: 155
    /// FORMAT: Error while updating scrap group {0} catalogue.
    /// PARAMS: @0: scrapGroupCode
    /// </summary>
    public const string AlarmCode_ScrapGroupUpdate = "PRM018";

    /// <summary>
    /// Alarm definition for AlarmId: 118
    /// FORMAT: Error while creating work order {0}: cannot parse value ({1}) in {2}
    /// PARAMS: @0: WorkOrder, @1: Value, @2: Field
    /// </summary>
    public const string AlarmCode_WorkOrderNotValid = "PRM021";

    /// <summary>
    /// Alarm definition for AlarmId: 129
    /// FORMAT: Can not shrink materials count for selected work order.
    /// </summary>
    public const string AlarmCode_MaterialsNotRemoved = "PRM022";

    /// <summary>
    /// Alarm definition for AlarmId: 130
    /// FORMAT: Error during changing materials count.
    /// </summary>
    public const string AlarmCode_MaterialsNotChanged = "PRM023";

    /// <summary>
    /// Alarm definition for AlarmId: 131
    /// FORMAT: Something went wrong while sending work order report to transfer table.
    /// </summary>
    public const string AlarmCode_WorkOrderReportCreateError = "PRM024";

    /// <summary>
    /// Alarm definition for AlarmId: 266
    /// FORMAT: Record is not unique.
    /// </summary>
    public const string AlarmCode_ProdManagerRecordNotUnique = "PRM027";

    /// <summary>
    /// Alarm definition for AlarmId: 267
    /// FORMAT: Violation of existing reference.
    /// </summary>
    public const string AlarmCode_ProdManagerExistingReferenceViolation = "PRM028";

    /// <summary>
    /// Alarm definition for AlarmId: 268
    /// FORMAT: Record is not found.
    /// </summary>
    public const string AlarmCode_ProdManagerRecordNotFound = "PRM029";

    /// <summary>
    /// Alarm definition for AlarmId: 269
    /// FORMAT: Operation not finished due to unexpected error.
    /// </summary>
    public const string AlarmCode_ProdManagerUnexpectedError = "PRM030";

    /// <summary>
    /// Alarm definition for AlarmId: 270
    /// FORMAT: Work order name is empty for remove operation.
    /// </summary>
    public const string AlarmCode_WorkOrderNameEmptyForRemoveOperation = "PRM031";

    /// <summary>
    /// Alarm definition for AlarmId: 271
    /// FORMAT: Billet reception not found in configuration.
    /// </summary>
    public const string AlarmCode_BilletReceptionNotFound = "PRM032";

    /// <summary>
    /// Alarm definition for AlarmId: 272
    /// FORMAT: Steel family {0} already esists.
    /// PARAMS: @0: steelFamilyCode
    /// </summary>
    public const string AlarmCode_SteelFamilyAlreadyExists = "PRM033";

    /// <summary>
    /// Alarm definition for AlarmId: 273
    /// FORMAT: Cannot generate product name.
    /// </summary>
    public const string AlarmCode_CannotGenerateProductName = "PRM034";

    /// <summary>
    /// Alarm definition for AlarmId: 274
    /// FORMAT: Work order {0} not updated.
    /// PARAMS: @0: workOrderName
    /// </summary>
    public const string AlarmCode_WorkOrderNotUpdated = "PRM035";

    /// <summary>
    /// Alarm definition for AlarmId: 275
    /// FORMAT: Work order {0} not found.
    /// PARAMS: @0: workOrderName
    /// </summary>
    public const string AlarmCode_WorkOrderNotFound = "PRM036";

    /// <summary>
    /// Alarm definition for AlarmId: 276
    /// FORMAT: Test work order cannot be created because of incorrect number of materials.
    /// </summary>
    public const string AlarmCode_TestOrderNotCreatedDueToWrongMaterialsNumber = "PRM037";

    /// <summary>
    /// Alarm definition for AlarmId: 277
    /// FORMAT: Work order not ended,
    /// </summary>
    public const string AlarmCode_WorkOrderNotEnded = "PRM038";

    /// <summary>
    /// Alarm definition for AlarmId: 279
    /// FORMAT: Work order {0} cannot be finished because coil for material {1} is not created.
    /// PARAMS: @0: workOrderName, @1: rawMaterialName
    /// </summary>
    public const string AlarmCode_CoilWorkOrderCannotBeFinishedDueToLackOfProduct = "PRM039";

    /// <summary>
    /// Alarm definition for AlarmId: 280
    /// FORMAT: Work order {0} cannot be finished because bar in coil for material {1} is not created.
    /// PARAMS: @0: workOrderName, @1: rawMaterialName
    /// </summary>
    public const string AlarmCode_BarInCoilWorkOrderCannotBeFinishedDueToLackOfProduct = "PRM040";

    /// <summary>
    /// Alarm definition for AlarmId: 408
    /// FORMAT: Coil report for billet {0} not created.
    /// PARAMS: @0: rawMaterialName
    /// </summary>
    public const string AlarmCode_CoilReportForBilletNotCreated = "PRM041";

    /// <summary>
    /// Alarm definition for AlarmId: 409
    /// FORMAT: Cannot create coil report for billet {0} because product cannot be found.
    /// PARAMS: @0: rawMaterialName
    /// </summary>
    public const string AlarmCode_CoilReportNotCreatedBecauseProductNotFound = "PRM042";

    /// <summary>
    /// Alarm definition for AlarmId: 410
    /// FORMAT: Coil report not created due to unexpected error.
    /// </summary>
    public const string AlarmCode_CoilReportCreateError = "PRM043";

    /// <summary>
    /// Alarm definition for AlarmId: 10423
    /// FORMAT: Bundle {0} report not created.
    /// PARAMS: @0: bundleName
    /// </summary>
    public const string AlarmCode_BundleReportNotCreated = "PRM044";

    /// <summary>
    /// Alarm definition for AlarmId: 10424
    /// FORMAT: Bundle report not created due to unexpected error.
    /// </summary>
    public const string AlarmCode_BundleReportCreateError = "PRM045";

    /// <summary>
    /// Alarm definition for AlarmId: 10431
    /// FORMAT: Product report for material {0} not created.
    /// PARAMS: @0: rawMaterialName
    /// </summary>
    public const string AlarmCode_ProductReportForMaterialNotCreated = "PRM046";

    /// <summary>
    /// Alarm definition for AlarmId: 10432
    /// FORMAT: Coil report not created due to unexpected error.
    /// </summary>
    public const string AlarmCode_ProductReportNotCreated = "PRM047";

    /// <summary>
    /// Alarm definition for AlarmId: 234
    /// FORMAT: Error while forcing material rating.
    /// </summary>
    public const string AlarmCode_QualityExpertForcingError = "QEX001";

    /// <summary>
    /// Alarm definition for AlarmId: 235
    /// FORMAT: Error while trying to toggle compensation.
    /// </summary>
    public const string AlarmCode_QualityExpertToggleCompensationError = "QEX002";

    /// <summary>
    /// Alarm definition for AlarmId: 236
    /// FORMAT: Error while calculating grading for material.
    /// </summary>
    public const string AlarmCode_QualityExpertGradingError = "QEX003";

    /// <summary>
    /// Alarm definition for AlarmId: 237
    /// FORMAT: Error while processing trigger for material {0} at area {1}
    /// PARAMS: @0: RawMaterialId, @1: AreaId
    /// </summary>
    public const string AlarmCode_QualityExpertTriggerProcessingError = "QEX004";

    /// <summary>
    /// Alarm definition for AlarmId: 238
    /// FORMAT: Error while updating signal definitions
    /// </summary>
    public const string AlarmCode_UpdateSignalDefinitionsError = "QEX005";

    /// <summary>
    /// Alarm definition for AlarmId: 386
    /// FORMAT: Violation of existing reference.
    /// </summary>
    public const string AlarmCode_QualityExpertExistingReferenceViolation = "QEX006";

    /// <summary>
    /// Alarm definition for AlarmId: 387
    /// FORMAT: Record is not found.
    /// </summary>
    public const string AlarmCode_QualityExpertRecordNotFound = "QEX007";

    /// <summary>
    /// Alarm definition for AlarmId: 388
    /// FORMAT: Record is not unique.
    /// </summary>
    public const string AlarmCode_QualityExpertRecordNotUnique = "QEX008";

    /// <summary>
    /// Alarm definition for AlarmId: 389
    /// FORMAT: Operation not finished due to unexpected error.
    /// </summary>
    public const string AlarmCode_QualityExpertUnexpectedError = "QEX009";

    /// <summary>
    /// Alarm definition for AlarmId: 41
    /// FORMAT: Error occured while performing operation on Defect Catalogue: {0}
    /// PARAMS: @0: message, @1: defectCode
    /// </summary>
    public const string AlarmCode_DefectCatalogGeneralError = "QTY001";

    /// <summary>
    /// Alarm definition for AlarmId: 66
    /// FORMAT: New entry with code {0} has been created in Defect Catalogue
    /// </summary>
    public const string AlarmCode_DefectCatalogCreate = "QTY002";

    /// <summary>
    /// Alarm definition for AlarmId: 103
    /// FORMAT: Defect Catalog entry with code {0} has been deleted
    /// PARAMS: @0: defectCode
    /// </summary>
    public const string AlarmCode_DefectCatalogDelete = "QTY003";

    /// <summary>
    /// Alarm definition for AlarmId: 104
    /// FORMAT: Defect Catalog entry with code {0} has been updated
    /// PARAMS: @0: defectCode
    /// </summary>
    public const string AlarmCode_DefectCatalogueUpdate = "QTY004";

    /// <summary>
    /// Alarm definition for AlarmId: 105
    /// FORMAT: Entry with code {0} can not be removed from Defect Catalogue because is in use
    /// PARAMS: @0: defectCode
    /// </summary>
    public const string AlarmCode_DefectCatDeleteNotPossible = "QTY005";

    /// <summary>
    /// Alarm definition for AlarmId: 106
    /// FORMAT: Defect Code {0} must be unique
    /// PARAMS: @0: defectCode
    /// </summary>
    public const string AlarmCode_DefectCodeNotUnique = "QTY006";

    /// <summary>
    /// Alarm definition for AlarmId: 107
    /// FORMAT: Failed to assign defects to product
    /// </summary>
    public const string AlarmCode_DefectAssignmentFailed = "QTY007";

    /// <summary>
    /// Alarm definition for AlarmId: 162
    /// FORMAT: Error while creating new Defect group. Defect group with specified code already exists in DB
    /// </summary>
    public const string AlarmCode_DefectGroupsExists = "QTY008";

    /// <summary>
    /// Alarm definition for AlarmId: 163
    /// FORMAT: Error while updating Defect Groups Catalogue.
    /// </summary>
    public const string AlarmCode_DefectGroupsUpdate = "QTY009";

    /// <summary>
    /// Alarm definition for AlarmId: 160
    /// FORMAT: Error while creating new Defect category. Defect category with specified code already exists in DB
    /// </summary>
    public const string AlarmCode_DefectCategoriesExists = "QTY010";

    /// <summary>
    /// Alarm definition for AlarmId: 161
    /// FORMAT: Error while updating Defect Category.
    /// </summary>
    public const string AlarmCode_DefectCategoriesUpdate = "QTY011";

    /// <summary>
    /// Alarm definition for AlarmId: 127
    /// FORMAT: Something went wrong while assigning quality to raw material.
    /// </summary>
    public const string AlarmCode_QualityAssigningToRawMaterialError = "QTY012";

    /// <summary>
    /// Alarm definition for AlarmId: 128
    /// FORMAT: Something went wrong while updating quality for raw material.
    /// </summary>
    public const string AlarmCode_QualityEditOfRawMaterialError = "QTY013";

    /// <summary>
    /// Alarm definition for AlarmId: 134
    /// FORMAT: There is already defined defects ({0}) for this asset
    /// PARAMS: @0: defectList
    /// </summary>
    public const string AlarmCode_QualityAssignmentCollision = "QTY014";

    /// <summary>
    /// Alarm definition for AlarmId: 135
    /// FORMAT: There is no quality inspection for current material
    /// </summary>
    public const string AlarmCode_MissingQuality = "QTY015";

    /// <summary>
    /// Alarm definition for AlarmId: 355
    /// FORMAT: Violation of existing reference.
    /// </summary>
    public const string AlarmCode_QualityExistingReferenceViolation = "QTY016";

    /// <summary>
    /// Alarm definition for AlarmId: 356
    /// FORMAT: Record is not found.
    /// </summary>
    public const string AlarmCode_QualityRecordNotFound = "QTY017";

    /// <summary>
    /// Alarm definition for AlarmId: 357
    /// FORMAT: Record is not unique.
    /// </summary>
    public const string AlarmCode_QualityRecordNotUnique = "QTY018";

    /// <summary>
    /// Alarm definition for AlarmId: 358
    /// FORMAT: Operation failed due to unexpected error.
    /// </summary>
    public const string AlarmCode_QualityUnexpectedError = "QTY019";

    /// <summary>
    /// Alarm definition for AlarmId: 359
    /// FORMAT: Quality is already assigned to raw materia;.
    /// </summary>
    public const string AlarmCode_QualityAlreadyAssigned = "QTY020";

    /// <summary>
    /// Alarm definition for AlarmId: 360
    /// FORMAT: Cannot find quality for raw material.
    /// </summary>
    public const string AlarmCode_RawMaterialQualityNotFound = "QTY021";

    /// <summary>
    /// Alarm definition for AlarmId: 76
    /// FORMAT: Error during roll creation
    /// </summary>
    public const string AlarmCode_RollSave = "RLS001";

    /// <summary>
    /// Alarm definition for AlarmId: 77
    /// FORMAT: Roll Already Exist in Data Base
    /// </summary>
    public const string AlarmCode_RollAlreadyExist = "RLS002";

    /// <summary>
    /// Alarm definition for AlarmId: 78
    /// FORMAT: Error during RollType save
    /// </summary>
    public const string AlarmCode_RollTypeSave = "RLS003";

    /// <summary>
    /// Alarm definition for AlarmId: 79
    /// FORMAT: Roll Type Already Exists
    /// </summary>
    public const string AlarmCode_RollTypeAlreadyExist = "RLS004";

    /// <summary>
    /// Alarm definition for AlarmId: 80
    /// FORMAT: Error during Groove Template save
    /// </summary>
    public const string AlarmCode_GrooveTemplateSaveError = "RLS005";

    /// <summary>
    /// Alarm definition for AlarmId: 81
    /// FORMAT: Groove Template already exists
    /// </summary>
    public const string AlarmCode_GrooveTemplateAlreadyExist = "RLS006";

    /// <summary>
    /// Alarm definition for AlarmId: 82
    /// FORMAT: Error during roll set save
    /// </summary>
    public const string AlarmCode_RollSetSaveError = "RLS007";

    /// <summary>
    /// Alarm definition for AlarmId: 83
    /// FORMAT: Roll Set already exist
    /// </summary>
    public const string AlarmCode_RollSetAlreadyExist = "RLS008";

    /// <summary>
    /// Alarm definition for AlarmId: 84
    /// FORMAT: Roll Set History save error
    /// </summary>
    public const string AlarmCode_RollSetHistorySaveError = "RLS009";

    /// <summary>
    /// Alarm definition for AlarmId: 85
    /// FORMAT: Failed to assemble rollset
    /// </summary>
    public const string AlarmCode_RollSetAssembleError = "RLS010";

    /// <summary>
    /// Alarm definition for AlarmId: 86
    /// FORMAT: RollSet history already exist
    /// </summary>
    public const string AlarmCode_RollSetHistoryAlreadyExist = "RLS011";

    /// <summary>
    /// Alarm definition for AlarmId: 87
    /// FORMAT: Cassette type save error
    /// </summary>
    public const string AlarmCode_CassetteTypeSaveError = "RLS012";

    /// <summary>
    /// Alarm definition for AlarmId: 88
    /// FORMAT: Cassette type already exist
    /// </summary>
    public const string AlarmCode_CassetteTypeAlreadyExist = "RLS013";

    /// <summary>
    /// Alarm definition for AlarmId: 89
    /// FORMAT: Error during Cassete save
    /// </summary>
    public const string AlarmCode_CassetteSaveError = "RLS014";

    /// <summary>
    /// Alarm definition for AlarmId: 90
    /// FORMAT: Cassette already exist
    /// </summary>
    public const string AlarmCode_CassetteAlreadyExist = "RLS015";

    /// <summary>
    /// Alarm definition for AlarmId: 91
    /// FORMAT: Roll Change operation Error
    /// </summary>
    public const string AlarmCode_RollChangeOperationError = "RLS016";

    /// <summary>
    /// Alarm definition for AlarmId: 193
    /// FORMAT: In stand {0} there is mounted groove with exceeded billets count limit
    /// PARAMS: @0: standName
    /// </summary>
    public const string AlarmCode_BilletsCountLimitExceeded = "RLS017";

    /// <summary>
    /// Alarm definition for AlarmId: 194
    /// FORMAT: In stand {0} there is mounted groove with exceeded weight limit
    /// PARAMS: @0: standName
    /// </summary>
    public const string AlarmCode_WeightLimitExceeded = "RSL018";

    /// <summary>
    /// Alarm definition for AlarmId: 195
    /// FORMAT: In stand {0} there is mounted groove with exceeded weight with coeff limit
    /// PARAMS: @0: standName
    /// </summary>
    public const string AlarmCode_WeightWithCoeffLimitExceeded = "RSL019";

    /// <summary>
    /// Alarm definition for AlarmId: 61
    /// FORMAT: Given list of structure telegram values is empty - telegram not exist in db
    /// </summary>
    public const string AlarmCode_EmptyTelegramValuesList = "STP001";

    /// <summary>
    /// Alarm definition for AlarmId: 62
    /// FORMAT: Wrong telegram id {0}
    /// PARAMS: @0: TelegramId
    /// </summary>
    public const string AlarmCode_NotExistingTelegram = "STP002";

    /// <summary>
    /// Alarm definition for AlarmId: 63
    /// FORMAT: Critical error when processing manager setup configuration for telegram id {0}
    /// PARAMS: @0: TelegramId
    /// </summary>
    public const string AlarmCode_TelegramSetupError = "STP003";

    /// <summary>
    /// Alarm definition for AlarmId: 68
    /// FORMAT: SocketException was thrown for telegram: {0}
    /// PARAMS: @0: TelegramId
    /// </summary>
    public const string AlarmCode_SocketException = "STP004";

    /// <summary>
    /// Alarm definition for AlarmId: 164
    /// FORMAT: Name or parameters are not uniqe.
    /// </summary>
    public const string AlarmCode_NotUniqueNameOrParameters = "STP005";

    /// <summary>
    /// Alarm definition for AlarmId: 165
    /// FORMAT: Setup not calculated
    /// </summary>
    public const string AlarmCode_SetupNotCalculated = "STP006";

    /// <summary>
    /// Alarm definition for AlarmId: 166
    /// FORMAT: Found multiple setups for {0} in WO {1}: {2}. First setup was selected
    /// PARAMS: @0: setupType, @1: workOrder, @2: setups, @3: setupType, @4: workOrder, @5: setups
    /// </summary>
    public const string AlarmCode_AmbiguousSetup = "STP007";

    /// <summary>
    /// Alarm definition for AlarmId: 167
    /// FORMAT: Not all optional setups was calculated for {0}
    /// PARAMS: @0: workOrder, @1: workOrder
    /// </summary>
    public const string AlarmCode_PartiallyCalculated = "STP008";

    /// <summary>
    /// Alarm definition for AlarmId: 176
    /// FORMAT: Could not send telegram to L1
    /// </summary>
    public const string AlarmCode_SetupNotSent = "STP009";

    /// <summary>
    /// Alarm definition for AlarmId: 177
    /// FORMAT: Setups are not valid
    /// </summary>
    public const string AlarmCode_SetupsNotValid = "STP010";

    /// <summary>
    /// Alarm definition for AlarmId: 206
    /// FORMAT: Setup value is not valid in given type
    /// </summary>
    public const string AlarmCode_SetupValueNotValidInGivenType = "STP011";

    /// <summary>
    /// Alarm definition for AlarmId: 207
    /// FORMAT: Setup value is out of range
    /// </summary>
    public const string AlarmCode_SetupValueOutOfRange = "STP012";

    /// <summary>
    /// Alarm definition for AlarmId: 239
    /// FORMAT: Setup {0} not created.
    /// PARAMS: @0: SetupName
    /// </summary>
    public const string AlarmCode_SetupNotCreated = "STP013";

    /// <summary>
    /// Alarm definition for AlarmId: 361
    /// FORMAT: Record is not unique.
    /// </summary>
    public const string AlarmCode_SetupRecordNotUnique = "STP014";

    /// <summary>
    /// Alarm definition for AlarmId: 362
    /// FORMAT: Violation of existing reference.
    /// </summary>
    public const string AlarmCode_SetupExistingReferenceViolation = "STP015";

    /// <summary>
    /// Alarm definition for AlarmId: 363
    /// FORMAT: Record is not found.
    /// </summary>
    public const string AlarmCode_SetupRecordNotFound = "STP016";

    /// <summary>
    /// Alarm definition for AlarmId: 364
    /// FORMAT: Operation not finished due to unexpected error.
    /// </summary>
    public const string AlarmCode_SetupUnexpectedError = "STP017";

    /// <summary>
    /// Alarm definition for AlarmId: 365
    /// FORMAT: Setup {0} not copied.
    /// PARAMS: @0: setupName
    /// </summary>
    public const string AlarmCode_SetupNotCopied = "STP018";

    /// <summary>
    /// Alarm definition for AlarmId: 366
    /// FORMAT: Error while creating setup configuration {0} in version {1}.
    /// PARAMS: @0: setupConfigurationName, @1: setupConfigurationVersion
    /// </summary>
    public const string AlarmCode_SetupConfigurationNotCreated = "STP019";

    /// <summary>
    /// Alarm definition for AlarmId: 367
    /// FORMAT: Error while updating setup configuration {0}.
    /// PARAMS: @0: SetupConfigurationName
    /// </summary>
    public const string AlarmCode_SetupConfigurationNotModified = "STP020";

    /// <summary>
    /// Alarm definition for AlarmId: 368
    /// FORMAT: Setup configuration not sent.
    /// </summary>
    public const string AlarmCode_SetupConfigurationNotSent = "STP021";

    /// <summary>
    /// Alarm definition for AlarmId: 369
    /// FORMAT: Error while cloning setup configuration {0}.
    /// PARAMS: @0: setupConfigurationName
    /// </summary>
    public const string AlarmCode_SetupConfigurationNotCloned = "STP022";

    /// <summary>
    /// Alarm definition for AlarmId: 370
    /// FORMAT: Error while creating version {0} of setup configuration {1}.
    /// PARAMS: @0: setupConfigurationVersion, @1: setupConfigurationName
    /// </summary>
    public const string AlarmCode_SetupConfigurationVersionNotCreated = "STP023";

    /// <summary>
    /// Alarm definition for AlarmId: 371
    /// FORMAT: Record is not unique.
    /// </summary>
    public const string AlarmCode_TcpProxyRecordNotUnique = "TCP001";

    /// <summary>
    /// Alarm definition for AlarmId: 372
    /// FORMAT: Violation of existing reference.
    /// </summary>
    public const string AlarmCode_TcpProxyExistingReferenceViolation = "TCP002";

    /// <summary>
    /// Alarm definition for AlarmId: 373
    /// FORMAT: Record is not found.
    /// </summary>
    public const string AlarmCode_TcpProxyRecordNotFound = "TCP003";

    /// <summary>
    /// Alarm definition for AlarmId: 374
    /// FORMAT: Operation not finished due to unexpected error.
    /// </summary>
    public const string AlarmCode_TcpProxyUnexpectedError = "TCP004";

    /// <summary>
    /// Alarm definition for AlarmId: 375
    /// FORMAT: TCP connection with {0}:{1} not opened.
    /// PARAMS: @0: IPAddress, @1: port
    /// </summary>
    public const string AlarmCode_TCPConnectionNotOpened = "TCP005";

    /// <summary>
    /// Alarm definition for AlarmId: 376
    /// FORMAT: Cannot find sender in TCP configuration.
    /// </summary>
    public const string AlarmCode_SenderNotFound = "TCP006";

    /// <summary>
    /// Alarm definition for AlarmId: 377
    /// FORMAT: Unable to receive acknowledge from {0}:{1}.
    /// PARAMS: @0: IPAddress, @1: port
    /// </summary>
    public const string AlarmCode_AcknowledgeNotReceived = "TCP007";

    /// <summary>
    /// Alarm definition for AlarmId: 378
    /// FORMAT: TCP connection with {0}:{1} not closed.
    /// PARAMS: @0: IPAddress, @1: port
    /// </summary>
    public const string AlarmCode_TCPConnectionNotClosed = "TCP008";

    /// <summary>
    /// Alarm definition for AlarmId: 379
    /// FORMAT: TCP telegram not sent to {0}:{1}.
    /// PARAMS: @0: IPAddress, @1: port
    /// </summary>
    public const string AlarmCode_TCPTelegramNotSent = "TCP009";

    /// <summary>
    /// Alarm definition for AlarmId: 380
    /// FORMAT: Ascii telegram not sent.
    /// </summary>
    public const string AlarmCode_AsciiTelegramNotSent = "TCP010";

    /// <summary>
    /// Alarm definition for AlarmId: 381
    /// FORMAT: Something went wrong while listening for {0}:{1}.
    /// PARAMS: @0: IPAddress, @1: port
    /// </summary>
    public const string AlarmCode_ErrorDuringListeningAddress = "TCP011";

    /// <summary>
    /// Alarm definition for AlarmId: 382
    /// FORMAT: Error during TCP client initialization.
    /// </summary>
    public const string AlarmCode_TCPClientNotInitialized = "TCP012";

    /// <summary>
    /// Alarm definition for AlarmId: 383
    /// FORMAT: Error while disconnecting TCP communication.
    /// </summary>
    public const string AlarmCode_CommunicationNotDisconnected = "TCP013";

    /// <summary>
    /// Alarm definition for AlarmId: 384
    /// FORMAT: Assembly {0} not found.
    /// PARAMS: @0: assembly
    /// </summary>
    public const string AlarmCode_AssemblyNotFOund = "TCP014";

    /// <summary>
    /// Alarm definition for AlarmId: 385
    /// FORMAT: Could not find type {0} is assembly {1}.
    /// PARAMS: @0: type, @1: assembly
    /// </summary>
    public const string AlarmCode_AssemblyTypeNotFound = "TCP015";

    /// <summary>
    /// Alarm definition for AlarmId: 151
    /// FORMAT: Test
    /// </summary>
    public const string AlarmCode_Test = "Test1";

    /// <summary>
    /// Alarm definition for AlarmId: 196
    /// FORMAT: Detected cobble in area {0}.
    /// PARAMS: @0: assetName
    /// </summary>
    public const string AlarmCode_CobbleDetected = "TRK001";

    /// <summary>
    /// Alarm definition for AlarmId: 253
    /// FORMAT: Something went wrong while creating product for material {0}.
    /// PARAMS: @0: rawMaterialName
    /// </summary>
    public const string AlarmCode_ProductCreatonForMaterialFailed = "TRK002";

    /// <summary>
    /// Alarm definition for AlarmId: 255
    /// FORMAT: For material {0} product already exists.
    /// PARAMS: @0: rawMaterialName
    /// </summary>
    public const string AlarmCode_ProductExistsForMaterial = "TRK003";

    /// <summary>
    /// Alarm definition for AlarmId: 256
    /// FORMAT: Cannot create product for dummy material {0}.
    /// PARAMS: @0: rawMaterialName
    /// </summary>
    public const string AlarmCode_CannotCreateProductForDummyMaterial = "TRK004";

    /// <summary>
    /// Alarm definition for AlarmId: 257
    /// FORMAT: Cannot create product because material {0} is scrapped.
    /// PARAMS: @0: rawMaterialName
    /// </summary>
    public const string AlarmCode_CannotCreateProductForScrappedMaterial = "TRK005";

    /// <summary>
    /// Alarm definition for AlarmId: 258
    /// FORMAT: Violation of existing reference.
    /// </summary>
    public const string AlarmCode_TrackingExistingReferenceViolation = "TRK006";

    /// <summary>
    /// Alarm definition for AlarmId: 406
    /// FORMAT: Record is not found.
    /// </summary>
    public const string AlarmCode_TrackingRecordNotFound = "TRK007";

    /// <summary>
    /// Alarm definition for AlarmId: 260
    /// FORMAT: Record is not unique.
    /// </summary>
    public const string AlarmCode_TrackingRecordNotUnique = "TRK008";

    /// <summary>
    /// Alarm definition for AlarmId: 261
    /// FORMAT: Operation not finished due to unexpected error.
    /// </summary>
    public const string AlarmCode_TrackingUnexpectedError = "TRK009";

    /// <summary>
    /// Alarm definition for AlarmId: 281
    /// FORMAT: Layer is not created because asset with code {0} is not layer area.
    /// PARAMS: @0: AreaCode
    /// </summary>
    public const string AlarmCode_LayerNotCreatedBecauseAreaIsNotLayerArea = "TRK010";

    /// <summary>
    /// Alarm definition for AlarmId: 282
    /// FORMAT: Parent material was not found in point with code {0}.
    /// PARAMS: @0: pointAssetCode
    /// </summary>
    public const string AlarmCode_ParentRawMaterialNotFoundInPoint = "TRK011";

    /// <summary>
    /// Alarm definition for AlarmId: 283
    /// FORMAT: Record was not unique while creating child material in asset with code {0}.
    /// PARAMS: @0: pointAssetCode
    /// </summary>
    public const string AlarmCode_RecordNotUniqueDuringChildCreation = "TRK012";

    /// <summary>
    /// Alarm definition for AlarmId: 284
    /// FORMAT: Violation of existing reference while creating child material in asset with code {0}.
    /// PARAMS: @0: pointAssetCode
    /// </summary>
    public const string AlarmCode_ExistingReferenceViolationDuringChildCreation = "TRK013";

    /// <summary>
    /// Alarm definition for AlarmId: 285
    /// FORMAT: Unexpected exception during child creation in point with code {0}.
    /// PARAMS: @0: pointAssetCode 
    /// </summary>
    public const string AlarmCode_UnexpectedErrorDuringChildCreation = "TRK014";

    /// <summary>
    /// Alarm definition for AlarmId: 286
    /// FORMAT: Record was not unique while verifying last divide in asset with code {0}.
    /// PARAMS: @0: pointAssetCode
    /// </summary>
    public const string AlarmCode_RecordNotUniqueDuringLastDivideVerification = "TRK015";

    /// <summary>
    /// Alarm definition for AlarmId: 287
    /// FORMAT: Violation of existing reference while verifying last divide in asset with code {0}.
    /// PARAMS: @0: pointAssetCode
    /// </summary>
    public const string AlarmCode_ExistingReferenceViolationDuringLastDivideVerification = "TRK016";

    /// <summary>
    /// Alarm definition for AlarmId: 288
    /// FORMAT: Unexpected exception while verifying last divide in asset with code {0}.
    /// PARAMS: @0: pointAssetCode
    /// </summary>
    public const string AlarmCode_UnexpectedErrorDuringLastDivideVerification = "TRK017";

    /// <summary>
    /// Alarm definition for AlarmId: 289
    /// FORMAT: Material not found on point on point with code {0}.
    /// PARAMS: @0: pointAssetCode
    /// </summary>
    public const string AlarmCode_MaterialNotFoundOnPoint = "TRK018";

    /// <summary>
    /// Alarm definition for AlarmId: 290
    /// FORMAT: Record was not unique while rejecting material.
    /// </summary>
    public const string AlarmCode_RecodrNotUniqueWhileRejectingRawMaterial = "TRK019";

    /// <summary>
    /// Alarm definition for AlarmId: 291
    /// FORMAT: Violation of existing reference while rejecting raw material.
    /// </summary>
    public const string AlarmCode_ExistingReferenceViolationDuringRawMaterialReject = "TRK020";

    /// <summary>
    /// Alarm definition for AlarmId: 292
    /// FORMAT: Unexpected exception while rejecting material.
    /// </summary>
    public const string AlarmCode_UnexpectedErrorDuringRawMaterialReject = "TRK021";

    /// <summary>
    /// Alarm definition for AlarmId: 293
    /// FORMAT: Point with code {0} is not layer,
    /// PARAMS: @0: pointAssetCode
    /// </summary>
    public const string AlarmCode_AssetIsNotLayer = "TRK022";

    /// <summary>
    /// Alarm definition for AlarmId: 294
    /// FORMAT: Nothing was discharged from layer with code {0}
    /// PARAMS: @0: layerAssetCode
    /// </summary>
    public const string AlarmCode_NothingDischargedFromLayer = "TRK023";

    /// <summary>
    /// Alarm definition for AlarmId: 295
    /// FORMAT: Material not removed from area with code {0}.
    /// PARAMS: @0: areaAssetCode
    /// </summary>
    public const string AlarmCode_MaterialNotRemovedFromArea = "TRK024";

    /// <summary>
    /// Alarm definition for AlarmId: 296
    /// FORMAT: Material from charging grid is not in collection type.
    /// </summary>
    public const string AlarmCode_MaterialInChargingGridNotInCollectionType = "TRK025";

    /// <summary>
    /// Alarm definition for AlarmId: 297
    /// FORMAT: Material not undischarged from charging grid.
    /// </summary>
    public const string AlarmCode_MaterialNotUndischargeFromChargingGrid = "TRK026";

    /// <summary>
    /// Alarm definition for AlarmId: 298
    /// FORMAT: Material not charged to charging grid.
    /// </summary>
    public const string AlarmCode_MaterialNotChargedToChargingGrid = "TRK027";

    /// <summary>
    /// Alarm definition for AlarmId: 299
    /// FORMAT: Material not uncharged from furnace.
    /// </summary>
    public const string AlarmCode_MaterialNotUnchargedFromFurnace = "TRK028";

    /// <summary>
    /// Alarm definition for AlarmId: 300
    /// FORMAT: Material not charged to furnace.
    /// </summary>
    public const string AlarmCode_MaterialNotChargedToFurnace = "TRK029";

    /// <summary>
    /// Alarm definition for AlarmId: 301
    /// FORMAT: Material not discharged from furnace.
    /// </summary>
    public const string AlarmCode_MaterialNotDischargedFromFurnace = "TRK030";

    /// <summary>
    /// Alarm definition for AlarmId: 302
    /// FORMAT: Material not undischarged from furnace,
    /// </summary>
    public const string AlarmCode_MaterialNotUndischargedFromFurnace = "TRK031";

    /// <summary>
    /// Alarm definition for AlarmId: 303
    /// FORMAT: Cannot find material to undischarge.
    /// </summary>
    public const string AlarmCode_CannotFindMaterialToUndischarge = "TRK032";

    /// <summary>
    /// Alarm definition for AlarmId: 304
    /// FORMAT: Material not charged on furnace exit.
    /// </summary>
    public const string AlarmCode_MaterialNotChargedToFurnaceExit = "TRK033";

    /// <summary>
    /// Alarm definition for AlarmId: 305
    /// FORMAT: Something went wrong while processing hard remove operation.
    /// </summary>
    public const string AlarmCode_MaterialNotHardRemoved = "TRK034";

    /// <summary>
    /// Alarm definition for AlarmId: 306
    /// FORMAT: Product cannot be undone.
    /// </summary>
    public const string AlarmCode_ProductCannotBeUndone = "TRK035";

    /// <summary>
    /// Alarm definition for AlarmId: 307
    /// FORMAT: Something wrong while product undo operation.
    /// </summary>
    public const string AlarmCode_ProductUndoFailed = "TRK036";

    /// <summary>
    /// Alarm definition for AlarmId: 308
    /// FORMAT: Material not unassigned.
    /// </summary>
    public const string AlarmCode_MaterialNotUnassigned = "TRK037";

    /// <summary>
    /// Alarm definition for AlarmId: 309
    /// FORMAT: Material not assigned.
    /// </summary>
    public const string AlarmCode_MaterialNotAssigned = "TRK038";

    /// <summary>
    /// Alarm definition for AlarmId: 310
    /// FORMAT: Cannot move materials because this operation is not allowed in area with code {0}.
    /// PARAMS: @0: areaAssetCode
    /// </summary>
    public const string AlarmCode_AreaNotMoveable = "TRK039";

    /// <summary>
    /// Alarm definition for AlarmId: 311
    /// FORMAT: Operation move forward for area with code {0} failed.
    /// PARAMS: @0: areaAssetCode
    /// </summary>
    public const string AlarmCode_AreaMoveForwardFailed = "TRK040";

    /// <summary>
    /// Alarm definition for AlarmId: 312
    /// FORMAT: Operation move backward for area with code {0} failed.
    /// PARAMS: @0: areaAssetCode
    /// </summary>
    public const string AlarmCode_AreaMoveBackwardFailed = "TRK041";

    /// <summary>
    /// Alarm definition for AlarmId: 313
    /// FORMAT: Cannot find layer in position {0} for area with code {1}.
    /// PARAMS: @0: positionNumber, @1: areaAssetCode
    /// </summary>
    public const string AlarmCode_CannotFindLayerInPosition = "TRK042";

    /// <summary>
    /// Alarm definition for AlarmId: 314
    /// FORMAT: Cannot paste material to layer with status {0}.
    /// PARAMS: @0: layerStatus
    /// </summary>
    public const string AlarmCode_LayerStatusPreventsPaste = "TRK043";

    /// <summary>
    /// Alarm definition for AlarmId: 315
    /// FORMAT: Cannot replace material position for area with code {0}.
    /// PARAMS: @0: areaAssetCode
    /// </summary>
    public const string AlarmCode_CannotReplaceMaterialPositionForArea = "TRK044";

    /// <summary>
    /// Alarm definition for AlarmId: 316
    /// FORMAT: Replace material position failed from position {0} in area with code {1} to position {2} in area with code {3}.
    /// PARAMS: @0: dragOrderSequence, @1: dragAssetCode, @2: dropOrderSequence, @3: dropAssetCode
    /// </summary>
    public const string AlarmCode_ReplaceMaterialPositionFailed = "TRK045";

    /// <summary>
    /// Alarm definition for AlarmId: 317
    /// FORMAT: Operation remove material from all areas failed.
    /// </summary>
    public const string AlarmCode_RemoveMaterialFromAllAreasFailed = "TRK046";

    /// <summary>
    /// Alarm definition for AlarmId: 318
    /// FORMAT: Cannot find layer with material.
    /// </summary>
    public const string AlarmCode_LayerWithMaterialNotFound = "TRK047";

    /// <summary>
    /// Alarm definition for AlarmId: 319
    /// FORMAT: Layer info is not in valid type.
    /// </summary>
    public const string AlarmCode_LayerInfoNotInValidType = "TRK048";

    /// <summary>
    /// Alarm definition for AlarmId: 320
    /// FORMAT: Material cut operation failed
    /// </summary>
    public const string AlarmCode_MaterialCutFailed = "TRK049";

    /// <summary>
    /// Alarm definition for AlarmId: 321
    /// FORMAT: Unexpected error while processing OCR message.
    /// </summary>
    public const string AlarmCode_UnexpectedExceptionDuringOCRMessageProcessing = "TRK050";

    /// <summary>
    /// Alarm definition for AlarmId: 323
    /// FORMAT: Unexpected exception while preparing message to L1.
    /// </summary>
    public const string AlarmCode_MessageToL1NotPrepared = "TRK051";

    /// <summary>
    /// Alarm definition for AlarmId: 405
    /// FORMAT: Product for material {0} not found. Cannot generate label.
    /// PARAMS: @0: l3MaterialId
    /// </summary>
    public const string AlarmCode_ProductForLabelNotFound = "TRK052";

    /// <summary>
    /// Alarm definition for AlarmId: 10414
    /// FORMAT: Cage closed for snap shear {0}.
    /// PARAMS: @0: assetCode
    /// </summary>
    public const string AlarmCode_ShapShearCageClosed = "TRK053";

    /// <summary>
    /// Alarm definition for AlarmId: 10421
    /// FORMAT: Failed to send accumulated equipment usage for material {0} with weight {1} and weight with coefficient {2}.
    /// PARAMS: @0: materialName, @1: materialWeight, @2: materialWeightWithcoefficient
    /// </summary>
    public const string AlarmCode_FailedToSendAccumulatedRollsUsageForMaterial = "TRK054";

    /// <summary>
    /// Alarm definition for AlarmId: 10422
    /// FORMAT: Failed to send accumulated equipment usage for material {0} with weight {1}.
    /// PARAMS: @0: materialName, @1: materialWeight
    /// </summary>
    public const string AlarmCode_FailedToSendAccumulatedEquipmentUsageForMaterial = "TRK055";

    /// <summary>
    /// Alarm definition for AlarmId: 10425
    /// FORMAT: Work order {0} status prevents bundle creation.
    /// PARAMS: @0: workOrderName
    /// </summary>
    public const string AlarmCode_WorkOrderStatusPreventsBundleCreation = "TRK056";

    /// <summary>
    /// Alarm definition for AlarmId: 10426
    /// FORMAT: Something went wrong while creating bundle for work order {0}.
    /// PARAMS: @0: workOrderName
    /// </summary>
    public const string AlarmCode_SomethingWentWrongWhileCreatingBundleForWorkOrder = "TRK057";

    /// <summary>
    /// Alarm definition for AlarmId: 390
    /// FORMAT: Record is not unique.
    /// </summary>
    public const string AlarmCode_WalkingBeamFurnaceExpertRecordNotUnique = "WBF001";

    /// <summary>
    /// Alarm definition for AlarmId: 391
    /// FORMAT: Violation of existing reference.
    /// </summary>
    public const string AlarmCode_WalkingBeamFurnaceExpertExistingReferenceViolation = "WBF002";

    /// <summary>
    /// Alarm definition for AlarmId: 392
    /// FORMAT: Record is not found.
    /// </summary>
    public const string AlarmCode_WalkingBeamFurnaceExpertRecordNotFound = "WBF003";

    /// <summary>
    /// Alarm definition for AlarmId: 393
    /// FORMAT: Operation not finished due to unexpected error.
    /// </summary>
    public const string AlarmCode_WalkingBeamFurnaceExpertUnexpectedError = "WBF004";

    /// <summary>
    /// Alarm definition for AlarmId: 136
    /// FORMAT: Error while transferring selected heat.
    /// </summary>
    public const string AlarmCode_TransferFailed = "YRD001";

    /// <summary>
    /// Alarm definition for AlarmId: 137
    /// FORMAT: Not enought space in target location ({0})
    /// PARAMS: @0: remainingSpace
    /// </summary>
    public const string AlarmCode_NotEnoughtSpace = "YRD002";

    /// <summary>
    /// Alarm definition for AlarmId: 138
    /// FORMAT: Error while creating materials in yard
    /// </summary>
    public const string AlarmCode_CreateMaterialsFail = "YRD003";

    /// <summary>
    /// Alarm definition for AlarmId: 139
    /// FORMAT: Can not take requested number of material ({0}) assigned to heat from location {1}
    /// PARAMS: @0: MaterialsNumber, @1: LocationName
    /// </summary>
    public const string AlarmCode_NoHeatsForGivenRequest = "YRD004";

    /// <summary>
    /// Alarm definition for AlarmId: 140
    /// FORMAT: Schedule does not have any work order without assigned materials
    /// </summary>
    public const string AlarmCode_NoChargingTaskForSchedule = "YRD005";

    /// <summary>
    /// Alarm definition for AlarmId: 141
    /// FORMAT: Selected work order is no longer first in queue to assign material
    /// </summary>
    public const string AlarmCode_OutdatedScheduleData = "YRD006";

    /// <summary>
    /// Alarm definition for AlarmId: 142
    /// FORMAT: Selected work order need only {0} materials
    /// PARAMS: @0: missingMaterialCount
    /// </summary>
    public const string AlarmCode_TooManyMaterials = "YRD007";

    /// <summary>
    /// Alarm definition for AlarmId: 143
    /// FORMAT: Materials are already assigned to another work order
    /// </summary>
    public const string AlarmCode_MaterialAlreadyAssigned = "YRD008";

    /// <summary>
    /// Alarm definition for AlarmId: 144
    /// FORMAT: Heat with name {0} already existing in system
    /// PARAMS: @0: heatName
    /// </summary>
    public const string AlarmCode_HeatExisting = "YRD009";

    /// <summary>
    /// Alarm definition for AlarmId: 145
    /// FORMAT: Cannot dispatch unfinished work order {0}
    /// PARAMS: @0: WorOrder
    /// </summary>
    public const string AlarmCode_DispatchUnfinishedWorkOrder = "YRD010";

    /// <summary>
    /// Alarm definition for AlarmId: 146
    /// FORMAT: No products found for given criteria ({0}). Data might be changed
    /// PARAMS: @0: requestedProductsNumber
    /// </summary>
    public const string AlarmCode_NoProductsForGivenRequest = "YRD011";

    /// <summary>
    /// Alarm definition for AlarmId: 147
    /// FORMAT: Error while dispatching WO
    /// </summary>
    public const string AlarmCode_DispatchFailed = "YRD012";

    /// <summary>
    /// Alarm definition for AlarmId: 148
    /// FORMAT: Error while relocating products
    /// </summary>
    public const string AlarmCode_ProductRelocationFail = "YRD013";

    /// <summary>
    /// Alarm definition for AlarmId: 149
    /// FORMAT: Can not reorder location. Data may be changed
    /// </summary>
    public const string AlarmCode_LocationReorderInvalidRequest = "YRD014";

    /// <summary>
    /// Alarm definition for AlarmId: 150
    /// FORMAT: Error when reordering location
    /// </summary>
    public const string AlarmCode_LocationReorderFail = "YRD015";

    /// <summary>
    /// Alarm definition for AlarmId: 400
    /// FORMAT: Record is not unique.
    /// </summary>
    public const string AlarmCode_YardsExpertRecordNotUnique = "YRD016";

    /// <summary>
    /// Alarm definition for AlarmId: 401
    /// FORMAT: Violation of existing reference.
    /// </summary>
    public const string AlarmCode_YardsExpertExistingReferenceViolation = "YRD017";

    /// <summary>
    /// Alarm definition for AlarmId: 402
    /// FORMAT: Record is not found.
    /// </summary>
    public const string AlarmCode_YardsExpertRecordNotFound = "YRD018";

    /// <summary>
    /// Alarm definition for AlarmId: 403
    /// FORMAT: Operation not finished due to unexpected error.
    /// </summary>
    public const string AlarmCode_YardsExpertUnexpectedError = "YRD019";

    /// <summary>
    /// Alarm definition for AlarmId: 67
    /// FORMAT: Failed To Generate Label
    /// </summary>
    public const string AlarmCode_FailedToGenerateLabel = "ZPC001";

    /// <summary>
    /// Alarm definition for AlarmId: 394
    /// FORMAT: Record is not unique.
    /// </summary>
    public const string AlarmCode_ZebraPrinterConnectorExpertRecordNotUnique = "ZPC002";

    /// <summary>
    /// Alarm definition for AlarmId: 395
    /// FORMAT: Violation of existing reference.
    /// </summary>
    public const string AlarmCode_ZebraPrinterConnectorExpertExistingReferenceViolation = "ZPC003";

    /// <summary>
    /// Alarm definition for AlarmId: 396
    /// FORMAT: Record is not found.
    /// </summary>
    public const string AlarmCode_ZebraPrinterConnectorExpertRecordNotFound = "ZPC004";

    /// <summary>
    /// Alarm definition for AlarmId: 397
    /// FORMAT: Operation not finished due to unexpected error.
    /// </summary>
    public const string AlarmCode_ZebraPrinterConnectorExpertUnexpectedError = "ZPC005";

    /// <summary>
    /// Alarm definition for AlarmId: 398
    /// FORMAT: Unexpected error while printing label.
    /// </summary>
    public const string AlarmCode_LabelNotPrinted = "ZPC006";

    /// <summary>
    /// Alarm definition for AlarmId: 399
    /// FORMAT: Error while requesting printer status.
    /// </summary>
    public const string AlarmCode_ErrorRequestingPrinterStatus = "ZPC007";

    /// <summary>
    /// Alarm definition for AlarmId: 10438
    /// FORMAT: Zebra printer warning: {0}
    /// PARAMS: @0: status
    /// </summary>
    public const string AlarmCode_ZebraPrinterWarnings = "ZPC008";

    /// <summary>
    /// Alarm definition for AlarmId: 10439
    /// FORMAT: Zebra printer error: {0}
    /// PARAMS: @0: status
    /// </summary>
    public const string AlarmCode_ZebraPrinterErrors = "ZPC009";

  }
}
